namespace GUI
{
    partial class CategoryManagement
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CategoryManagement));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.label_CM = new System.Windows.Forms.Label();
            this.searchbox_cate = new Bunifu.UI.WinForms.BunifuTextBox();
            this.addgroup_cate = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.addpic_cate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pic_cate = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tb2_cate = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lb1_ID = new Bunifu.UI.WinForms.BunifuLabel();
            this.tb1_cate = new Bunifu.UI.WinForms.BunifuTextBox();
            this.detail_cate = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.Column3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Column7 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Des_cate = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.search_category = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.addBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.addgroup_cate.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pic_cate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.detail_cate)).BeginInit();
            this.SuspendLayout();
            // 
            // label_CM
            // 
            this.label_CM.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.label_CM.AutoSize = true;
            this.label_CM.Font = new System.Drawing.Font("Poppins SemiBold", 19.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label_CM.Location = new System.Drawing.Point(18, 33);
            this.label_CM.Name = "label_CM";
            this.label_CM.Size = new System.Drawing.Size(431, 60);
            this.label_CM.TabIndex = 3;
            this.label_CM.Text = "Category Management";
            // 
            // searchbox_cate
            // 
            this.searchbox_cate.AcceptsReturn = false;
            this.searchbox_cate.AcceptsTab = false;
            this.searchbox_cate.AnimationSpeed = 200;
            this.searchbox_cate.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.searchbox_cate.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.searchbox_cate.AutoSizeHeight = true;
            this.searchbox_cate.BackColor = System.Drawing.Color.Transparent;
            this.searchbox_cate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchbox_cate.BackgroundImage")));
            this.searchbox_cate.BorderColorActive = System.Drawing.Color.PowderBlue;
            this.searchbox_cate.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchbox_cate.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.searchbox_cate.BorderColorIdle = System.Drawing.Color.Silver;
            this.searchbox_cate.BorderRadius = 20;
            this.searchbox_cate.BorderThickness = 1;
            this.searchbox_cate.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.searchbox_cate.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.searchbox_cate.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.searchbox_cate.DefaultFont = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.searchbox_cate.DefaultText = "";
            this.searchbox_cate.FillColor = System.Drawing.Color.White;
            this.searchbox_cate.HideSelection = true;
            this.searchbox_cate.IconLeft = null;
            this.searchbox_cate.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchbox_cate.IconPadding = 10;
            this.searchbox_cate.IconRight = null;
            this.searchbox_cate.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchbox_cate.Lines = new string[0];
            this.searchbox_cate.Location = new System.Drawing.Point(3, 96);
            this.searchbox_cate.MaxLength = 32767;
            this.searchbox_cate.MinimumSize = new System.Drawing.Size(1, 1);
            this.searchbox_cate.Modified = false;
            this.searchbox_cate.Multiline = false;
            this.searchbox_cate.Name = "searchbox_cate";
            stateProperties1.BorderColor = System.Drawing.Color.PowderBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchbox_cate.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.searchbox_cate.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchbox_cate.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchbox_cate.OnIdleState = stateProperties4;
            this.searchbox_cate.Padding = new System.Windows.Forms.Padding(3);
            this.searchbox_cate.PasswordChar = '\0';
            this.searchbox_cate.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.searchbox_cate.PlaceholderText = "Search here...";
            this.searchbox_cate.ReadOnly = false;
            this.searchbox_cate.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.searchbox_cate.SelectedText = "";
            this.searchbox_cate.SelectionLength = 0;
            this.searchbox_cate.SelectionStart = 0;
            this.searchbox_cate.ShortcutsEnabled = true;
            this.searchbox_cate.Size = new System.Drawing.Size(508, 45);
            this.searchbox_cate.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.searchbox_cate.TabIndex = 4;
            this.searchbox_cate.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.searchbox_cate.TextMarginBottom = 0;
            this.searchbox_cate.TextMarginLeft = 3;
            this.searchbox_cate.TextMarginTop = 1;
            this.searchbox_cate.TextPlaceholder = "Search here...";
            this.searchbox_cate.UseSystemPasswordChar = false;
            this.searchbox_cate.WordWrap = true;
            // 
            // addgroup_cate
            // 
            this.addgroup_cate.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.addgroup_cate.BackColor = System.Drawing.Color.White;
            this.addgroup_cate.BorderColor = System.Drawing.Color.LightGray;
            this.addgroup_cate.BorderRadius = 1;
            this.addgroup_cate.BorderThickness = 1;
            this.addgroup_cate.Controls.Add(this.addpic_cate);
            this.addgroup_cate.Controls.Add(this.pic_cate);
            this.addgroup_cate.Controls.Add(this.addBtn);
            this.addgroup_cate.Controls.Add(this.bunifuLabel1);
            this.addgroup_cate.Controls.Add(this.tb2_cate);
            this.addgroup_cate.Controls.Add(this.lb1_ID);
            this.addgroup_cate.Controls.Add(this.tb1_cate);
            this.addgroup_cate.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addgroup_cate.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addgroup_cate.LabelIndent = 10;
            this.addgroup_cate.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.addgroup_cate.Location = new System.Drawing.Point(851, 161);
            this.addgroup_cate.Name = "addgroup_cate";
            this.addgroup_cate.Size = new System.Drawing.Size(302, 504);
            this.addgroup_cate.TabIndex = 14;
            this.addgroup_cate.TabStop = false;
            this.addgroup_cate.Text = "Add Category Group";
            // 
            // addpic_cate
            // 
            this.addpic_cate.AllowAnimations = true;
            this.addpic_cate.AllowMouseEffects = true;
            this.addpic_cate.AllowToggling = false;
            this.addpic_cate.AnimationSpeed = 200;
            this.addpic_cate.AutoGenerateColors = false;
            this.addpic_cate.AutoRoundBorders = false;
            this.addpic_cate.AutoSizeLeftIcon = true;
            this.addpic_cate.AutoSizeRightIcon = true;
            this.addpic_cate.BackColor = System.Drawing.Color.Transparent;
            this.addpic_cate.BackColor1 = System.Drawing.SystemColors.ButtonFace;
            this.addpic_cate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addpic_cate.BackgroundImage")));
            this.addpic_cate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addpic_cate.ButtonText = "Add Picture";
            this.addpic_cate.ButtonTextMarginLeft = 0;
            this.addpic_cate.ColorContrastOnClick = 45;
            this.addpic_cate.ColorContrastOnHover = 45;
            this.addpic_cate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.addpic_cate.CustomizableEdges = borderEdges1;
            this.addpic_cate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addpic_cate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addpic_cate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addpic_cate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addpic_cate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.addpic_cate.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addpic_cate.ForeColor = System.Drawing.Color.Gray;
            this.addpic_cate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addpic_cate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addpic_cate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addpic_cate.IconMarginLeft = 11;
            this.addpic_cate.IconPadding = 10;
            this.addpic_cate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addpic_cate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addpic_cate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addpic_cate.IconSize = 25;
            this.addpic_cate.IdleBorderColor = System.Drawing.SystemColors.AppWorkspace;
            this.addpic_cate.IdleBorderRadius = 1;
            this.addpic_cate.IdleBorderThickness = 1;
            this.addpic_cate.IdleFillColor = System.Drawing.SystemColors.ButtonFace;
            this.addpic_cate.IdleIconLeftImage = null;
            this.addpic_cate.IdleIconRightImage = null;
            this.addpic_cate.IndicateFocus = false;
            this.addpic_cate.Location = new System.Drawing.Point(173, 291);
            this.addpic_cate.Name = "addpic_cate";
            this.addpic_cate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addpic_cate.OnDisabledState.BorderRadius = 1;
            this.addpic_cate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addpic_cate.OnDisabledState.BorderThickness = 1;
            this.addpic_cate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addpic_cate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addpic_cate.OnDisabledState.IconLeftImage = null;
            this.addpic_cate.OnDisabledState.IconRightImage = null;
            this.addpic_cate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addpic_cate.onHoverState.BorderRadius = 1;
            this.addpic_cate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addpic_cate.onHoverState.BorderThickness = 1;
            this.addpic_cate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addpic_cate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addpic_cate.onHoverState.IconLeftImage = null;
            this.addpic_cate.onHoverState.IconRightImage = null;
            this.addpic_cate.OnIdleState.BorderColor = System.Drawing.SystemColors.AppWorkspace;
            this.addpic_cate.OnIdleState.BorderRadius = 1;
            this.addpic_cate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addpic_cate.OnIdleState.BorderThickness = 1;
            this.addpic_cate.OnIdleState.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.addpic_cate.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.addpic_cate.OnIdleState.IconLeftImage = null;
            this.addpic_cate.OnIdleState.IconRightImage = null;
            this.addpic_cate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addpic_cate.OnPressedState.BorderRadius = 1;
            this.addpic_cate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addpic_cate.OnPressedState.BorderThickness = 1;
            this.addpic_cate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addpic_cate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addpic_cate.OnPressedState.IconLeftImage = null;
            this.addpic_cate.OnPressedState.IconRightImage = null;
            this.addpic_cate.Size = new System.Drawing.Size(110, 31);
            this.addpic_cate.TabIndex = 10;
            this.addpic_cate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addpic_cate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addpic_cate.TextMarginLeft = 0;
            this.addpic_cate.TextPadding = new System.Windows.Forms.Padding(0);
            this.addpic_cate.UseDefaultRadiusAndThickness = true;
            // 
            // pic_cate
            // 
            this.pic_cate.AllowFocused = false;
            this.pic_cate.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pic_cate.AutoSizeHeight = true;
            this.pic_cate.BorderRadius = 55;
            this.pic_cate.Image = ((System.Drawing.Image)(resources.GetObject("pic_cate.Image")));
            this.pic_cate.IsCircle = true;
            this.pic_cate.Location = new System.Drawing.Point(172, 175);
            this.pic_cate.Name = "pic_cate";
            this.pic_cate.Size = new System.Drawing.Size(111, 111);
            this.pic_cate.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pic_cate.TabIndex = 8;
            this.pic_cate.TabStop = false;
            this.pic_cate.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(22, 112);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(56, 30);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "Name:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tb2_cate
            // 
            this.tb2_cate.AcceptsReturn = false;
            this.tb2_cate.AcceptsTab = false;
            this.tb2_cate.AnimationSpeed = 200;
            this.tb2_cate.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb2_cate.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb2_cate.AutoSizeHeight = true;
            this.tb2_cate.BackColor = System.Drawing.Color.Transparent;
            this.tb2_cate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb2_cate.BackgroundImage")));
            this.tb2_cate.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb2_cate.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb2_cate.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb2_cate.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb2_cate.BorderRadius = 20;
            this.tb2_cate.BorderThickness = 1;
            this.tb2_cate.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tb2_cate.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb2_cate.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb2_cate.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb2_cate.DefaultText = "";
            this.tb2_cate.FillColor = System.Drawing.Color.White;
            this.tb2_cate.HideSelection = true;
            this.tb2_cate.IconLeft = null;
            this.tb2_cate.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb2_cate.IconPadding = 10;
            this.tb2_cate.IconRight = null;
            this.tb2_cate.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb2_cate.Lines = new string[0];
            this.tb2_cate.Location = new System.Drawing.Point(75, 112);
            this.tb2_cate.MaxLength = 32767;
            this.tb2_cate.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb2_cate.Modified = false;
            this.tb2_cate.Multiline = false;
            this.tb2_cate.Name = "tb2_cate";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb2_cate.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb2_cate.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb2_cate.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb2_cate.OnIdleState = stateProperties8;
            this.tb2_cate.Padding = new System.Windows.Forms.Padding(3);
            this.tb2_cate.PasswordChar = '\0';
            this.tb2_cate.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb2_cate.PlaceholderText = "Enter Category Name";
            this.tb2_cate.ReadOnly = false;
            this.tb2_cate.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb2_cate.SelectedText = "";
            this.tb2_cate.SelectionLength = 0;
            this.tb2_cate.SelectionStart = 0;
            this.tb2_cate.ShortcutsEnabled = true;
            this.tb2_cate.Size = new System.Drawing.Size(209, 43);
            this.tb2_cate.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb2_cate.TabIndex = 2;
            this.tb2_cate.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb2_cate.TextMarginBottom = 0;
            this.tb2_cate.TextMarginLeft = 3;
            this.tb2_cate.TextMarginTop = 1;
            this.tb2_cate.TextPlaceholder = "Enter Category Name";
            this.tb2_cate.UseSystemPasswordChar = false;
            this.tb2_cate.WordWrap = true;
            // 
            // lb1_ID
            // 
            this.lb1_ID.AllowParentOverrides = false;
            this.lb1_ID.AutoEllipsis = false;
            this.lb1_ID.CursorType = null;
            this.lb1_ID.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lb1_ID.Location = new System.Drawing.Point(50, 64);
            this.lb1_ID.Name = "lb1_ID";
            this.lb1_ID.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lb1_ID.Size = new System.Drawing.Size(20, 30);
            this.lb1_ID.TabIndex = 1;
            this.lb1_ID.Text = "ID:";
            this.lb1_ID.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lb1_ID.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tb1_cate
            // 
            this.tb1_cate.AcceptsReturn = false;
            this.tb1_cate.AcceptsTab = false;
            this.tb1_cate.AnimationSpeed = 200;
            this.tb1_cate.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb1_cate.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb1_cate.AutoSizeHeight = true;
            this.tb1_cate.BackColor = System.Drawing.Color.Transparent;
            this.tb1_cate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb1_cate.BackgroundImage")));
            this.tb1_cate.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb1_cate.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb1_cate.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb1_cate.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb1_cate.BorderRadius = 20;
            this.tb1_cate.BorderThickness = 1;
            this.tb1_cate.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tb1_cate.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb1_cate.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb1_cate.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb1_cate.DefaultText = "";
            this.tb1_cate.FillColor = System.Drawing.Color.White;
            this.tb1_cate.HideSelection = true;
            this.tb1_cate.IconLeft = null;
            this.tb1_cate.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb1_cate.IconPadding = 10;
            this.tb1_cate.IconRight = null;
            this.tb1_cate.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb1_cate.Lines = new string[0];
            this.tb1_cate.Location = new System.Drawing.Point(75, 64);
            this.tb1_cate.MaxLength = 32767;
            this.tb1_cate.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb1_cate.Modified = false;
            this.tb1_cate.Multiline = false;
            this.tb1_cate.Name = "tb1_cate";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb1_cate.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb1_cate.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb1_cate.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb1_cate.OnIdleState = stateProperties12;
            this.tb1_cate.Padding = new System.Windows.Forms.Padding(3);
            this.tb1_cate.PasswordChar = '\0';
            this.tb1_cate.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb1_cate.PlaceholderText = "Enter Category ID";
            this.tb1_cate.ReadOnly = false;
            this.tb1_cate.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb1_cate.SelectedText = "";
            this.tb1_cate.SelectionLength = 0;
            this.tb1_cate.SelectionStart = 0;
            this.tb1_cate.ShortcutsEnabled = true;
            this.tb1_cate.Size = new System.Drawing.Size(209, 43);
            this.tb1_cate.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb1_cate.TabIndex = 0;
            this.tb1_cate.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb1_cate.TextMarginBottom = 0;
            this.tb1_cate.TextMarginLeft = 3;
            this.tb1_cate.TextMarginTop = 1;
            this.tb1_cate.TextPlaceholder = "Enter Category ID";
            this.tb1_cate.UseSystemPasswordChar = false;
            this.tb1_cate.WordWrap = true;
            // 
            // detail_cate
            // 
            this.detail_cate.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.detail_cate.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.detail_cate.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.detail_cate.BackgroundColor = System.Drawing.Color.WhiteSmoke;
            this.detail_cate.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.detail_cate.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleVertical;
            this.detail_cate.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DarkSlateGray;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(63)))), ((int)(((byte)(63)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.detail_cate.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.detail_cate.ColumnHeadersHeight = 40;
            this.detail_cate.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Column3,
            this.Column7,
            this.Des_cate});
            this.detail_cate.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
            this.detail_cate.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.detail_cate.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.detail_cate.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            this.detail_cate.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.detail_cate.CurrentTheme.BackColor = System.Drawing.Color.DarkSlateGray;
            this.detail_cate.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
            this.detail_cate.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DarkSlateGray;
            this.detail_cate.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.detail_cate.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.detail_cate.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(63)))), ((int)(((byte)(63)))));
            this.detail_cate.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.detail_cate.CurrentTheme.Name = null;
            this.detail_cate.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            this.detail_cate.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.detail_cate.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.detail_cate.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            this.detail_cate.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.detail_cate.DefaultCellStyle = dataGridViewCellStyle4;
            this.detail_cate.EnableHeadersVisualStyles = false;
            this.detail_cate.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
            this.detail_cate.HeaderBackColor = System.Drawing.Color.DarkSlateGray;
            this.detail_cate.HeaderBgColor = System.Drawing.Color.Empty;
            this.detail_cate.HeaderForeColor = System.Drawing.Color.White;
            this.detail_cate.Location = new System.Drawing.Point(3, 158);
            this.detail_cate.Name = "detail_cate";
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.Teal;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.detail_cate.RowHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.detail_cate.RowHeadersVisible = false;
            this.detail_cate.RowHeadersWidth = 62;
            this.detail_cate.RowTemplate.DefaultCellStyle.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.detail_cate.RowTemplate.Height = 40;
            this.detail_cate.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.detail_cate.Size = new System.Drawing.Size(842, 499);
            this.detail_cate.TabIndex = 13;
            this.detail_cate.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.DarkSlateGray;
            // 
            // Column3
            // 
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Column3.DefaultCellStyle = dataGridViewCellStyle3;
            this.Column3.HeaderText = "Category";
            this.Column3.MinimumWidth = 8;
            this.Column3.Name = "Column3";
            // 
            // Column7
            // 
            this.Column7.HeaderText = "Cate_ID";
            this.Column7.MinimumWidth = 8;
            this.Column7.Name = "Column7";
            // 
            // Des_cate
            // 
            this.Des_cate.HeaderText = "Description";
            this.Des_cate.MinimumWidth = 8;
            this.Des_cate.Name = "Des_cate";
            // 
            // search_category
            // 
            this.search_category.AllowAnimations = true;
            this.search_category.AllowMouseEffects = true;
            this.search_category.AllowToggling = false;
            this.search_category.AnimationSpeed = 200;
            this.search_category.AutoGenerateColors = false;
            this.search_category.AutoRoundBorders = false;
            this.search_category.AutoSizeLeftIcon = true;
            this.search_category.AutoSizeRightIcon = true;
            this.search_category.BackColor = System.Drawing.Color.Transparent;
            this.search_category.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.search_category.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("search_category.BackgroundImage")));
            this.search_category.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.search_category.ButtonText = "Search";
            this.search_category.ButtonTextMarginLeft = 0;
            this.search_category.ColorContrastOnClick = 45;
            this.search_category.ColorContrastOnHover = 45;
            this.search_category.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.search_category.CustomizableEdges = borderEdges3;
            this.search_category.DialogResult = System.Windows.Forms.DialogResult.None;
            this.search_category.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.search_category.DisabledFillColor = System.Drawing.Color.Empty;
            this.search_category.DisabledForecolor = System.Drawing.Color.Empty;
            this.search_category.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.search_category.Font = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.search_category.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.search_category.IconLeft = null;
            this.search_category.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.search_category.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.search_category.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.search_category.IconMarginLeft = 11;
            this.search_category.IconPadding = 10;
            this.search_category.IconRight = null;
            this.search_category.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.search_category.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.search_category.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.search_category.IconSize = 25;
            this.search_category.IdleBorderColor = System.Drawing.Color.Empty;
            this.search_category.IdleBorderRadius = 0;
            this.search_category.IdleBorderThickness = 0;
            this.search_category.IdleFillColor = System.Drawing.Color.Empty;
            this.search_category.IdleIconLeftImage = null;
            this.search_category.IdleIconRightImage = null;
            this.search_category.IndicateFocus = false;
            this.search_category.Location = new System.Drawing.Point(544, 96);
            this.search_category.Name = "search_category";
            this.search_category.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.search_category.OnDisabledState.BorderRadius = 30;
            this.search_category.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.search_category.OnDisabledState.BorderThickness = 1;
            this.search_category.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.search_category.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.search_category.OnDisabledState.IconLeftImage = null;
            this.search_category.OnDisabledState.IconRightImage = null;
            this.search_category.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.search_category.onHoverState.BorderRadius = 30;
            this.search_category.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.search_category.onHoverState.BorderThickness = 1;
            this.search_category.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.search_category.onHoverState.ForeColor = System.Drawing.Color.White;
            this.search_category.onHoverState.IconLeftImage = null;
            this.search_category.onHoverState.IconRightImage = null;
            this.search_category.OnIdleState.BorderColor = System.Drawing.Color.CadetBlue;
            this.search_category.OnIdleState.BorderRadius = 30;
            this.search_category.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.search_category.OnIdleState.BorderThickness = 1;
            this.search_category.OnIdleState.FillColor = System.Drawing.Color.CadetBlue;
            this.search_category.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.search_category.OnIdleState.IconLeftImage = null;
            this.search_category.OnIdleState.IconRightImage = null;
            this.search_category.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.search_category.OnPressedState.BorderRadius = 30;
            this.search_category.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.search_category.OnPressedState.BorderThickness = 1;
            this.search_category.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.search_category.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.search_category.OnPressedState.IconLeftImage = null;
            this.search_category.OnPressedState.IconRightImage = null;
            this.search_category.Size = new System.Drawing.Size(104, 45);
            this.search_category.TabIndex = 17;
            this.search_category.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.search_category.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.search_category.TextMarginLeft = 0;
            this.search_category.TextPadding = new System.Windows.Forms.Padding(0);
            this.search_category.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = false;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.CadetBlue;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Edit";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges4;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Poppins", 12F);
            this.bunifuButton22.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 25;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.White;
            this.bunifuButton22.IdleBorderRadius = 30;
            this.bunifuButton22.IdleBorderThickness = 1;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.CadetBlue;
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.IdleIconRightImage")));
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new System.Drawing.Point(590, 681);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 30;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 1;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.BorderRadius = 30;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 1;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.BorderRadius = 30;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 1;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.CadetBlue;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.OnIdleState.IconRightImage")));
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.BorderRadius = 30;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 1;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(96, 47);
            this.bunifuButton22.TabIndex = 25;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(5, 2, 0, 0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = false;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Delete";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges5;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Poppins", 12F);
            this.bunifuButton21.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.White;
            this.bunifuButton21.IdleBorderRadius = 30;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.IdleIconRightImage")));
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(716, 681);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 30;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 30;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.BorderRadius = 30;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.OnIdleState.IconRightImage")));
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 30;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(117, 47);
            this.bunifuButton21.TabIndex = 24;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(5, 2, 0, 0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            // 
            // addBtn
            // 
            this.addBtn.AllowAnimations = false;
            this.addBtn.AllowMouseEffects = true;
            this.addBtn.AllowToggling = false;
            this.addBtn.AnimationSpeed = 200;
            this.addBtn.AutoGenerateColors = false;
            this.addBtn.AutoRoundBorders = false;
            this.addBtn.AutoSizeLeftIcon = true;
            this.addBtn.AutoSizeRightIcon = true;
            this.addBtn.BackColor = System.Drawing.Color.Transparent;
            this.addBtn.BackColor1 = System.Drawing.Color.CadetBlue;
            this.addBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addBtn.BackgroundImage")));
            this.addBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.ButtonText = "Add";
            this.addBtn.ButtonTextMarginLeft = 0;
            this.addBtn.ColorContrastOnClick = 45;
            this.addBtn.ColorContrastOnHover = 45;
            this.addBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.addBtn.CustomizableEdges = borderEdges2;
            this.addBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.addBtn.Font = new System.Drawing.Font("Poppins", 12F);
            this.addBtn.ForeColor = System.Drawing.Color.White;
            this.addBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addBtn.IconMarginLeft = 11;
            this.addBtn.IconPadding = 10;
            this.addBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addBtn.IconSize = 25;
            this.addBtn.IdleBorderColor = System.Drawing.Color.White;
            this.addBtn.IdleBorderRadius = 30;
            this.addBtn.IdleBorderThickness = 1;
            this.addBtn.IdleFillColor = System.Drawing.Color.CadetBlue;
            this.addBtn.IdleIconLeftImage = null;
            this.addBtn.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("addBtn.IdleIconRightImage")));
            this.addBtn.IndicateFocus = false;
            this.addBtn.Location = new System.Drawing.Point(108, 416);
            this.addBtn.Name = "addBtn";
            this.addBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addBtn.OnDisabledState.BorderRadius = 30;
            this.addBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.OnDisabledState.BorderThickness = 1;
            this.addBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addBtn.OnDisabledState.IconLeftImage = null;
            this.addBtn.OnDisabledState.IconRightImage = null;
            this.addBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addBtn.onHoverState.BorderRadius = 30;
            this.addBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.onHoverState.BorderThickness = 1;
            this.addBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addBtn.onHoverState.IconLeftImage = null;
            this.addBtn.onHoverState.IconRightImage = null;
            this.addBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.addBtn.OnIdleState.BorderRadius = 30;
            this.addBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.OnIdleState.BorderThickness = 1;
            this.addBtn.OnIdleState.FillColor = System.Drawing.Color.CadetBlue;
            this.addBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.addBtn.OnIdleState.IconLeftImage = null;
            this.addBtn.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("addBtn.OnIdleState.IconRightImage")));
            this.addBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addBtn.OnPressedState.BorderRadius = 30;
            this.addBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.OnPressedState.BorderThickness = 1;
            this.addBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addBtn.OnPressedState.IconLeftImage = null;
            this.addBtn.OnPressedState.IconRightImage = null;
            this.addBtn.Size = new System.Drawing.Size(98, 47);
            this.addBtn.TabIndex = 23;
            this.addBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addBtn.TextMarginLeft = 0;
            this.addBtn.TextPadding = new System.Windows.Forms.Padding(5, 2, 0, 0);
            this.addBtn.UseDefaultRadiusAndThickness = true;
            // 
            // CategoryManagement
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.bunifuButton22);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.search_category);
            this.Controls.Add(this.addgroup_cate);
            this.Controls.Add(this.detail_cate);
            this.Controls.Add(this.searchbox_cate);
            this.Controls.Add(this.label_CM);
            this.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "CategoryManagement";
            this.Size = new System.Drawing.Size(1185, 825);
            this.addgroup_cate.ResumeLayout(false);
            this.addgroup_cate.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pic_cate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.detail_cate)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label_CM;
        private Bunifu.UI.WinForms.BunifuTextBox searchbox_cate;
        private Bunifu.UI.WinForms.BunifuGroupBox addgroup_cate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 addpic_cate;
        private Bunifu.UI.WinForms.BunifuPictureBox pic_cate;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox tb2_cate;
        private Bunifu.UI.WinForms.BunifuLabel lb1_ID;
        private Bunifu.UI.WinForms.BunifuTextBox tb1_cate;
        private Bunifu.UI.WinForms.BunifuDataGridView detail_cate;
        private System.Windows.Forms.DataGridViewTextBoxColumn Column3;
        private System.Windows.Forms.DataGridViewTextBoxColumn Column7;
        private System.Windows.Forms.DataGridViewTextBoxColumn Des_cate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton search_category;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 addBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
    }
}
