
namespace GUI
{
    partial class AddUserForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddUserForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties73 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties74 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties75 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties76 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties77 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties78 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties79 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties80 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties81 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties82 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties83 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties84 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties85 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties86 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties87 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties88 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties89 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties90 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties91 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties92 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties93 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties94 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties95 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties96 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tbPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbLogin = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbLastName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cbUserRole = new System.Windows.Forms.ComboBox();
            this.bunifuLabel12 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbFirstName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel15 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel14 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btAddPcUser = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.btFemale = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.rdbFemale = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.rdbMale = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.pcUser = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.HireDate = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btCanCel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel13 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lbForm = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pcUser)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 16.125F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(241, -104);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(247, 51);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "Add New User";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.White;
            this.bunifuPanel1.BorderRadius = 1;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.tbPhone);
            this.bunifuPanel1.Controls.Add(this.tbEmail);
            this.bunifuPanel1.Controls.Add(this.tbPassword);
            this.bunifuPanel1.Controls.Add(this.tbLogin);
            this.bunifuPanel1.Controls.Add(this.tbLastName);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.cbUserRole);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel12);
            this.bunifuPanel1.Controls.Add(this.tbFirstName);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel15);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel14);
            this.bunifuPanel1.Controls.Add(this.btAddPcUser);
            this.bunifuPanel1.Controls.Add(this.bunifuGroupBox1);
            this.bunifuPanel1.Controls.Add(this.pcUser);
            this.bunifuPanel1.Controls.Add(this.HireDate);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel7);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel6);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel5);
            this.bunifuPanel1.Controls.Add(this.btCanCel);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel13);
            this.bunifuPanel1.Controls.Add(this.btAdd);
            this.bunifuPanel1.Location = new System.Drawing.Point(11, 88);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(743, 617);
            this.bunifuPanel1.TabIndex = 3;
            // 
            // tbPhone
            // 
            this.tbPhone.AcceptsReturn = false;
            this.tbPhone.AcceptsTab = false;
            this.tbPhone.AnimationSpeed = 200;
            this.tbPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPhone.AutoSizeHeight = true;
            this.tbPhone.BackColor = System.Drawing.Color.White;
            this.tbPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPhone.BackgroundImage")));
            this.tbPhone.BorderColorActive = System.Drawing.Color.White;
            this.tbPhone.BorderColorDisabled = System.Drawing.SystemColors.Window;
            this.tbPhone.BorderColorHover = System.Drawing.Color.White;
            this.tbPhone.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbPhone.BorderRadius = 10;
            this.tbPhone.BorderThickness = 1;
            this.tbPhone.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPhone.DefaultFont = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbPhone.DefaultText = "";
            this.tbPhone.FillColor = System.Drawing.Color.White;
            this.tbPhone.HideSelection = true;
            this.tbPhone.IconLeft = null;
            this.tbPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPhone.IconPadding = 10;
            this.tbPhone.IconRight = null;
            this.tbPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPhone.Lines = new string[0];
            this.tbPhone.Location = new System.Drawing.Point(387, 338);
            this.tbPhone.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbPhone.MaxLength = 32767;
            this.tbPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPhone.Modified = false;
            this.tbPhone.Multiline = false;
            this.tbPhone.Name = "tbPhone";
            stateProperties73.BorderColor = System.Drawing.Color.White;
            stateProperties73.FillColor = System.Drawing.Color.Empty;
            stateProperties73.ForeColor = System.Drawing.Color.Empty;
            stateProperties73.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPhone.OnActiveState = stateProperties73;
            stateProperties74.BorderColor = System.Drawing.SystemColors.Window;
            stateProperties74.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties74.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties74.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbPhone.OnDisabledState = stateProperties74;
            stateProperties75.BorderColor = System.Drawing.Color.White;
            stateProperties75.FillColor = System.Drawing.Color.Empty;
            stateProperties75.ForeColor = System.Drawing.Color.Empty;
            stateProperties75.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPhone.OnHoverState = stateProperties75;
            stateProperties76.BorderColor = System.Drawing.Color.DimGray;
            stateProperties76.FillColor = System.Drawing.Color.White;
            stateProperties76.ForeColor = System.Drawing.Color.Empty;
            stateProperties76.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPhone.OnIdleState = stateProperties76;
            this.tbPhone.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbPhone.PasswordChar = '\0';
            this.tbPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPhone.PlaceholderText = "Enter text";
            this.tbPhone.ReadOnly = false;
            this.tbPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPhone.SelectedText = "";
            this.tbPhone.SelectionLength = 0;
            this.tbPhone.SelectionStart = 0;
            this.tbPhone.ShortcutsEnabled = true;
            this.tbPhone.Size = new System.Drawing.Size(339, 58);
            this.tbPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbPhone.TabIndex = 35;
            this.tbPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPhone.TextMarginBottom = 0;
            this.tbPhone.TextMarginLeft = 3;
            this.tbPhone.TextMarginTop = 1;
            this.tbPhone.TextPlaceholder = "Enter text";
            this.tbPhone.UseSystemPasswordChar = false;
            this.tbPhone.WordWrap = true;
            // 
            // tbEmail
            // 
            this.tbEmail.AcceptsReturn = false;
            this.tbEmail.AcceptsTab = false;
            this.tbEmail.AnimationSpeed = 200;
            this.tbEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbEmail.AutoSizeHeight = true;
            this.tbEmail.BackColor = System.Drawing.Color.White;
            this.tbEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbEmail.BackgroundImage")));
            this.tbEmail.BorderColorActive = System.Drawing.Color.White;
            this.tbEmail.BorderColorDisabled = System.Drawing.SystemColors.Window;
            this.tbEmail.BorderColorHover = System.Drawing.Color.White;
            this.tbEmail.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbEmail.BorderRadius = 10;
            this.tbEmail.BorderThickness = 1;
            this.tbEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.DefaultFont = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbEmail.DefaultText = "";
            this.tbEmail.FillColor = System.Drawing.Color.White;
            this.tbEmail.HideSelection = true;
            this.tbEmail.IconLeft = null;
            this.tbEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.IconPadding = 10;
            this.tbEmail.IconRight = null;
            this.tbEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.Lines = new string[0];
            this.tbEmail.Location = new System.Drawing.Point(17, 338);
            this.tbEmail.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbEmail.MaxLength = 32767;
            this.tbEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbEmail.Modified = false;
            this.tbEmail.Multiline = false;
            this.tbEmail.Name = "tbEmail";
            stateProperties77.BorderColor = System.Drawing.Color.White;
            stateProperties77.FillColor = System.Drawing.Color.Empty;
            stateProperties77.ForeColor = System.Drawing.Color.Empty;
            stateProperties77.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnActiveState = stateProperties77;
            stateProperties78.BorderColor = System.Drawing.SystemColors.Window;
            stateProperties78.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties78.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties78.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbEmail.OnDisabledState = stateProperties78;
            stateProperties79.BorderColor = System.Drawing.Color.White;
            stateProperties79.FillColor = System.Drawing.Color.Empty;
            stateProperties79.ForeColor = System.Drawing.Color.Empty;
            stateProperties79.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnHoverState = stateProperties79;
            stateProperties80.BorderColor = System.Drawing.Color.DimGray;
            stateProperties80.FillColor = System.Drawing.Color.White;
            stateProperties80.ForeColor = System.Drawing.Color.Empty;
            stateProperties80.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnIdleState = stateProperties80;
            this.tbEmail.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbEmail.PasswordChar = '\0';
            this.tbEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbEmail.PlaceholderText = "Enter text";
            this.tbEmail.ReadOnly = false;
            this.tbEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbEmail.SelectedText = "";
            this.tbEmail.SelectionLength = 0;
            this.tbEmail.SelectionStart = 0;
            this.tbEmail.ShortcutsEnabled = true;
            this.tbEmail.Size = new System.Drawing.Size(339, 58);
            this.tbEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbEmail.TabIndex = 34;
            this.tbEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbEmail.TextMarginBottom = 0;
            this.tbEmail.TextMarginLeft = 3;
            this.tbEmail.TextMarginTop = 1;
            this.tbEmail.TextPlaceholder = "Enter text";
            this.tbEmail.UseSystemPasswordChar = false;
            this.tbEmail.WordWrap = true;
            // 
            // tbPassword
            // 
            this.tbPassword.AcceptsReturn = false;
            this.tbPassword.AcceptsTab = false;
            this.tbPassword.AnimationSpeed = 200;
            this.tbPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPassword.AutoSizeHeight = true;
            this.tbPassword.BackColor = System.Drawing.Color.White;
            this.tbPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPassword.BackgroundImage")));
            this.tbPassword.BorderColorActive = System.Drawing.Color.White;
            this.tbPassword.BorderColorDisabled = System.Drawing.SystemColors.Window;
            this.tbPassword.BorderColorHover = System.Drawing.Color.White;
            this.tbPassword.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbPassword.BorderRadius = 10;
            this.tbPassword.BorderThickness = 1;
            this.tbPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.DefaultFont = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbPassword.DefaultText = "";
            this.tbPassword.FillColor = System.Drawing.Color.White;
            this.tbPassword.HideSelection = true;
            this.tbPassword.IconLeft = null;
            this.tbPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.IconPadding = 10;
            this.tbPassword.IconRight = null;
            this.tbPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPassword.Lines = new string[0];
            this.tbPassword.Location = new System.Drawing.Point(387, 234);
            this.tbPassword.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbPassword.MaxLength = 32767;
            this.tbPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPassword.Modified = false;
            this.tbPassword.Multiline = false;
            this.tbPassword.Name = "tbPassword";
            stateProperties81.BorderColor = System.Drawing.Color.White;
            stateProperties81.FillColor = System.Drawing.Color.Empty;
            stateProperties81.ForeColor = System.Drawing.Color.Empty;
            stateProperties81.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnActiveState = stateProperties81;
            stateProperties82.BorderColor = System.Drawing.SystemColors.Window;
            stateProperties82.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties82.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties82.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbPassword.OnDisabledState = stateProperties82;
            stateProperties83.BorderColor = System.Drawing.Color.White;
            stateProperties83.FillColor = System.Drawing.Color.Empty;
            stateProperties83.ForeColor = System.Drawing.Color.Empty;
            stateProperties83.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnHoverState = stateProperties83;
            stateProperties84.BorderColor = System.Drawing.Color.DimGray;
            stateProperties84.FillColor = System.Drawing.Color.White;
            stateProperties84.ForeColor = System.Drawing.Color.Empty;
            stateProperties84.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPassword.OnIdleState = stateProperties84;
            this.tbPassword.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbPassword.PasswordChar = '\0';
            this.tbPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPassword.PlaceholderText = "Enter text";
            this.tbPassword.ReadOnly = false;
            this.tbPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPassword.SelectedText = "";
            this.tbPassword.SelectionLength = 0;
            this.tbPassword.SelectionStart = 0;
            this.tbPassword.ShortcutsEnabled = true;
            this.tbPassword.Size = new System.Drawing.Size(339, 58);
            this.tbPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbPassword.TabIndex = 33;
            this.tbPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPassword.TextMarginBottom = 0;
            this.tbPassword.TextMarginLeft = 3;
            this.tbPassword.TextMarginTop = 1;
            this.tbPassword.TextPlaceholder = "Enter text";
            this.tbPassword.UseSystemPasswordChar = false;
            this.tbPassword.WordWrap = true;
            // 
            // tbLogin
            // 
            this.tbLogin.AcceptsReturn = false;
            this.tbLogin.AcceptsTab = false;
            this.tbLogin.AnimationSpeed = 200;
            this.tbLogin.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbLogin.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbLogin.AutoSizeHeight = true;
            this.tbLogin.BackColor = System.Drawing.Color.White;
            this.tbLogin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbLogin.BackgroundImage")));
            this.tbLogin.BorderColorActive = System.Drawing.Color.White;
            this.tbLogin.BorderColorDisabled = System.Drawing.SystemColors.Window;
            this.tbLogin.BorderColorHover = System.Drawing.Color.White;
            this.tbLogin.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbLogin.BorderRadius = 10;
            this.tbLogin.BorderThickness = 1;
            this.tbLogin.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbLogin.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbLogin.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLogin.DefaultFont = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbLogin.DefaultText = "";
            this.tbLogin.FillColor = System.Drawing.Color.White;
            this.tbLogin.HideSelection = true;
            this.tbLogin.IconLeft = null;
            this.tbLogin.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLogin.IconPadding = 10;
            this.tbLogin.IconRight = null;
            this.tbLogin.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLogin.Lines = new string[0];
            this.tbLogin.Location = new System.Drawing.Point(17, 234);
            this.tbLogin.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbLogin.MaxLength = 32767;
            this.tbLogin.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbLogin.Modified = false;
            this.tbLogin.Multiline = false;
            this.tbLogin.Name = "tbLogin";
            stateProperties85.BorderColor = System.Drawing.Color.White;
            stateProperties85.FillColor = System.Drawing.Color.Empty;
            stateProperties85.ForeColor = System.Drawing.Color.Empty;
            stateProperties85.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLogin.OnActiveState = stateProperties85;
            stateProperties86.BorderColor = System.Drawing.SystemColors.Window;
            stateProperties86.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties86.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties86.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbLogin.OnDisabledState = stateProperties86;
            stateProperties87.BorderColor = System.Drawing.Color.White;
            stateProperties87.FillColor = System.Drawing.Color.Empty;
            stateProperties87.ForeColor = System.Drawing.Color.Empty;
            stateProperties87.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLogin.OnHoverState = stateProperties87;
            stateProperties88.BorderColor = System.Drawing.Color.DimGray;
            stateProperties88.FillColor = System.Drawing.Color.White;
            stateProperties88.ForeColor = System.Drawing.Color.Empty;
            stateProperties88.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLogin.OnIdleState = stateProperties88;
            this.tbLogin.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbLogin.PasswordChar = '\0';
            this.tbLogin.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbLogin.PlaceholderText = "Enter text";
            this.tbLogin.ReadOnly = false;
            this.tbLogin.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbLogin.SelectedText = "";
            this.tbLogin.SelectionLength = 0;
            this.tbLogin.SelectionStart = 0;
            this.tbLogin.ShortcutsEnabled = true;
            this.tbLogin.Size = new System.Drawing.Size(339, 58);
            this.tbLogin.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbLogin.TabIndex = 32;
            this.tbLogin.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbLogin.TextMarginBottom = 0;
            this.tbLogin.TextMarginLeft = 3;
            this.tbLogin.TextMarginTop = 1;
            this.tbLogin.TextPlaceholder = "Enter text";
            this.tbLogin.UseSystemPasswordChar = false;
            this.tbLogin.WordWrap = true;
            // 
            // tbLastName
            // 
            this.tbLastName.AcceptsReturn = false;
            this.tbLastName.AcceptsTab = false;
            this.tbLastName.AnimationSpeed = 200;
            this.tbLastName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbLastName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbLastName.AutoSizeHeight = true;
            this.tbLastName.BackColor = System.Drawing.Color.White;
            this.tbLastName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbLastName.BackgroundImage")));
            this.tbLastName.BorderColorActive = System.Drawing.Color.White;
            this.tbLastName.BorderColorDisabled = System.Drawing.SystemColors.Window;
            this.tbLastName.BorderColorHover = System.Drawing.Color.White;
            this.tbLastName.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbLastName.BorderRadius = 10;
            this.tbLastName.BorderThickness = 1;
            this.tbLastName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbLastName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbLastName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastName.DefaultFont = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbLastName.DefaultText = "";
            this.tbLastName.FillColor = System.Drawing.Color.White;
            this.tbLastName.HideSelection = true;
            this.tbLastName.IconLeft = null;
            this.tbLastName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastName.IconPadding = 10;
            this.tbLastName.IconRight = null;
            this.tbLastName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastName.Lines = new string[0];
            this.tbLastName.Location = new System.Drawing.Point(445, 49);
            this.tbLastName.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbLastName.MaxLength = 32767;
            this.tbLastName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbLastName.Modified = false;
            this.tbLastName.Multiline = false;
            this.tbLastName.Name = "tbLastName";
            stateProperties89.BorderColor = System.Drawing.Color.White;
            stateProperties89.FillColor = System.Drawing.Color.Empty;
            stateProperties89.ForeColor = System.Drawing.Color.Empty;
            stateProperties89.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastName.OnActiveState = stateProperties89;
            stateProperties90.BorderColor = System.Drawing.SystemColors.Window;
            stateProperties90.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties90.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties90.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbLastName.OnDisabledState = stateProperties90;
            stateProperties91.BorderColor = System.Drawing.Color.White;
            stateProperties91.FillColor = System.Drawing.Color.Empty;
            stateProperties91.ForeColor = System.Drawing.Color.Empty;
            stateProperties91.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastName.OnHoverState = stateProperties91;
            stateProperties92.BorderColor = System.Drawing.Color.DimGray;
            stateProperties92.FillColor = System.Drawing.Color.White;
            stateProperties92.ForeColor = System.Drawing.Color.Empty;
            stateProperties92.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastName.OnIdleState = stateProperties92;
            this.tbLastName.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbLastName.PasswordChar = '\0';
            this.tbLastName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbLastName.PlaceholderText = "Enter text";
            this.tbLastName.ReadOnly = false;
            this.tbLastName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbLastName.SelectedText = "";
            this.tbLastName.SelectionLength = 0;
            this.tbLastName.SelectionStart = 0;
            this.tbLastName.ShortcutsEnabled = true;
            this.tbLastName.Size = new System.Drawing.Size(281, 58);
            this.tbLastName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbLastName.TabIndex = 31;
            this.tbLastName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbLastName.TextMarginBottom = 0;
            this.tbLastName.TextMarginLeft = 3;
            this.tbLastName.TextMarginTop = 1;
            this.tbLastName.TextPlaceholder = "Enter text";
            this.tbLastName.UseSystemPasswordChar = false;
            this.tbLastName.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.SystemColors.Window;
            this.bunifuLabel2.Location = new System.Drawing.Point(445, 107);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(120, 42);
            this.bunifuLabel2.TabIndex = 30;
            this.bunifuLabel2.Text = "User Role";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cbUserRole
            // 
            this.cbUserRole.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbUserRole.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cbUserRole.FormattingEnabled = true;
            this.cbUserRole.Items.AddRange(new object[] {
            "1. Admin",
            "2. Employee"});
            this.cbUserRole.Location = new System.Drawing.Point(445, 143);
            this.cbUserRole.Name = "cbUserRole";
            this.cbUserRole.Size = new System.Drawing.Size(281, 50);
            this.cbUserRole.TabIndex = 29;
            // 
            // bunifuLabel12
            // 
            this.bunifuLabel12.AllowParentOverrides = false;
            this.bunifuLabel12.AutoEllipsis = false;
            this.bunifuLabel12.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel12.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel12.Font = new System.Drawing.Font("Segoe UI Semibold", 16.125F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuLabel12.Location = new System.Drawing.Point(232, -77);
            this.bunifuLabel12.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel12.Name = "bunifuLabel12";
            this.bunifuLabel12.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel12.Size = new System.Drawing.Size(247, 51);
            this.bunifuLabel12.TabIndex = 4;
            this.bunifuLabel12.Text = "Add New User";
            this.bunifuLabel12.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel12.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbFirstName
            // 
            this.tbFirstName.AcceptsReturn = false;
            this.tbFirstName.AcceptsTab = false;
            this.tbFirstName.AnimationSpeed = 200;
            this.tbFirstName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbFirstName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbFirstName.AutoSizeHeight = true;
            this.tbFirstName.BackColor = System.Drawing.Color.White;
            this.tbFirstName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbFirstName.BackgroundImage")));
            this.tbFirstName.BorderColorActive = System.Drawing.Color.White;
            this.tbFirstName.BorderColorDisabled = System.Drawing.SystemColors.Window;
            this.tbFirstName.BorderColorHover = System.Drawing.Color.White;
            this.tbFirstName.BorderColorIdle = System.Drawing.Color.DimGray;
            this.tbFirstName.BorderRadius = 10;
            this.tbFirstName.BorderThickness = 1;
            this.tbFirstName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbFirstName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbFirstName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstName.DefaultFont = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbFirstName.DefaultText = "";
            this.tbFirstName.FillColor = System.Drawing.Color.White;
            this.tbFirstName.HideSelection = true;
            this.tbFirstName.IconLeft = null;
            this.tbFirstName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstName.IconPadding = 10;
            this.tbFirstName.IconRight = null;
            this.tbFirstName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstName.Lines = new string[0];
            this.tbFirstName.Location = new System.Drawing.Point(144, 49);
            this.tbFirstName.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbFirstName.MaxLength = 32767;
            this.tbFirstName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbFirstName.Modified = false;
            this.tbFirstName.Multiline = false;
            this.tbFirstName.Name = "tbFirstName";
            stateProperties93.BorderColor = System.Drawing.Color.White;
            stateProperties93.FillColor = System.Drawing.Color.Empty;
            stateProperties93.ForeColor = System.Drawing.Color.Empty;
            stateProperties93.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstName.OnActiveState = stateProperties93;
            stateProperties94.BorderColor = System.Drawing.SystemColors.Window;
            stateProperties94.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties94.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties94.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbFirstName.OnDisabledState = stateProperties94;
            stateProperties95.BorderColor = System.Drawing.Color.White;
            stateProperties95.FillColor = System.Drawing.Color.Empty;
            stateProperties95.ForeColor = System.Drawing.Color.Empty;
            stateProperties95.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstName.OnHoverState = stateProperties95;
            stateProperties96.BorderColor = System.Drawing.Color.DimGray;
            stateProperties96.FillColor = System.Drawing.Color.White;
            stateProperties96.ForeColor = System.Drawing.Color.Empty;
            stateProperties96.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstName.OnIdleState = stateProperties96;
            this.tbFirstName.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tbFirstName.PasswordChar = '\0';
            this.tbFirstName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbFirstName.PlaceholderText = "Enter text";
            this.tbFirstName.ReadOnly = false;
            this.tbFirstName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbFirstName.SelectedText = "";
            this.tbFirstName.SelectionLength = 0;
            this.tbFirstName.SelectionStart = 0;
            this.tbFirstName.ShortcutsEnabled = true;
            this.tbFirstName.Size = new System.Drawing.Size(281, 58);
            this.tbFirstName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbFirstName.TabIndex = 27;
            this.tbFirstName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbFirstName.TextMarginBottom = 0;
            this.tbFirstName.TextMarginLeft = 3;
            this.tbFirstName.TextMarginTop = 1;
            this.tbFirstName.TextPlaceholder = "Enter text";
            this.tbFirstName.UseSystemPasswordChar = false;
            this.tbFirstName.WordWrap = true;
            // 
            // bunifuLabel15
            // 
            this.bunifuLabel15.AllowParentOverrides = false;
            this.bunifuLabel15.AutoEllipsis = false;
            this.bunifuLabel15.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel15.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel15.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel15.ForeColor = System.Drawing.SystemColors.Window;
            this.bunifuLabel15.Location = new System.Drawing.Point(445, 13);
            this.bunifuLabel15.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel15.Name = "bunifuLabel15";
            this.bunifuLabel15.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel15.Size = new System.Drawing.Size(137, 42);
            this.bunifuLabel15.TabIndex = 26;
            this.bunifuLabel15.Text = "Last Name";
            this.bunifuLabel15.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel15.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel14
            // 
            this.bunifuLabel14.AllowParentOverrides = false;
            this.bunifuLabel14.AutoEllipsis = false;
            this.bunifuLabel14.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel14.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel14.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel14.ForeColor = System.Drawing.SystemColors.Window;
            this.bunifuLabel14.Location = new System.Drawing.Point(144, 13);
            this.bunifuLabel14.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel14.Name = "bunifuLabel14";
            this.bunifuLabel14.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel14.Size = new System.Drawing.Size(138, 42);
            this.bunifuLabel14.TabIndex = 24;
            this.bunifuLabel14.Text = "First Name";
            this.bunifuLabel14.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel14.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btAddPcUser
            // 
            this.btAddPcUser.AllowAnimations = true;
            this.btAddPcUser.AllowMouseEffects = true;
            this.btAddPcUser.AllowToggling = false;
            this.btAddPcUser.AnimationSpeed = 200;
            this.btAddPcUser.AutoGenerateColors = false;
            this.btAddPcUser.AutoRoundBorders = false;
            this.btAddPcUser.AutoSizeLeftIcon = true;
            this.btAddPcUser.AutoSizeRightIcon = true;
            this.btAddPcUser.BackColor = System.Drawing.Color.Transparent;
            this.btAddPcUser.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btAddPcUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btAddPcUser.BackgroundImage")));
            this.btAddPcUser.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAddPcUser.ButtonText = "Upload";
            this.btAddPcUser.ButtonTextMarginLeft = 0;
            this.btAddPcUser.ColorContrastOnClick = 45;
            this.btAddPcUser.ColorContrastOnHover = 45;
            this.btAddPcUser.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btAddPcUser.CustomizableEdges = borderEdges10;
            this.btAddPcUser.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btAddPcUser.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btAddPcUser.DisabledFillColor = System.Drawing.Color.Empty;
            this.btAddPcUser.DisabledForecolor = System.Drawing.Color.Empty;
            this.btAddPcUser.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btAddPcUser.Font = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btAddPcUser.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btAddPcUser.IconLeft = null;
            this.btAddPcUser.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btAddPcUser.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btAddPcUser.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btAddPcUser.IconMarginLeft = 11;
            this.btAddPcUser.IconPadding = 10;
            this.btAddPcUser.IconRight = null;
            this.btAddPcUser.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btAddPcUser.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btAddPcUser.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btAddPcUser.IconSize = 25;
            this.btAddPcUser.IdleBorderColor = System.Drawing.Color.Empty;
            this.btAddPcUser.IdleBorderRadius = 0;
            this.btAddPcUser.IdleBorderThickness = 0;
            this.btAddPcUser.IdleFillColor = System.Drawing.Color.Empty;
            this.btAddPcUser.IdleIconLeftImage = null;
            this.btAddPcUser.IdleIconRightImage = null;
            this.btAddPcUser.IndicateFocus = false;
            this.btAddPcUser.Location = new System.Drawing.Point(16, 145);
            this.btAddPcUser.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.btAddPcUser.Name = "btAddPcUser";
            this.btAddPcUser.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAddPcUser.OnDisabledState.BorderRadius = 1;
            this.btAddPcUser.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAddPcUser.OnDisabledState.BorderThickness = 1;
            this.btAddPcUser.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAddPcUser.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAddPcUser.OnDisabledState.IconLeftImage = null;
            this.btAddPcUser.OnDisabledState.IconRightImage = null;
            this.btAddPcUser.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAddPcUser.onHoverState.BorderRadius = 1;
            this.btAddPcUser.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAddPcUser.onHoverState.BorderThickness = 1;
            this.btAddPcUser.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAddPcUser.onHoverState.ForeColor = System.Drawing.Color.Transparent;
            this.btAddPcUser.onHoverState.IconLeftImage = null;
            this.btAddPcUser.onHoverState.IconRightImage = null;
            this.btAddPcUser.OnIdleState.BorderColor = System.Drawing.Color.MediumTurquoise;
            this.btAddPcUser.OnIdleState.BorderRadius = 1;
            this.btAddPcUser.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAddPcUser.OnIdleState.BorderThickness = 1;
            this.btAddPcUser.OnIdleState.FillColor = System.Drawing.Color.Azure;
            this.btAddPcUser.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btAddPcUser.OnIdleState.IconLeftImage = null;
            this.btAddPcUser.OnIdleState.IconRightImage = null;
            this.btAddPcUser.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAddPcUser.OnPressedState.BorderRadius = 1;
            this.btAddPcUser.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAddPcUser.OnPressedState.BorderThickness = 1;
            this.btAddPcUser.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAddPcUser.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btAddPcUser.OnPressedState.IconLeftImage = null;
            this.btAddPcUser.OnPressedState.IconRightImage = null;
            this.btAddPcUser.Size = new System.Drawing.Size(109, 31);
            this.btAddPcUser.TabIndex = 22;
            this.btAddPcUser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btAddPcUser.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btAddPcUser.TextMarginLeft = 0;
            this.btAddPcUser.TextPadding = new System.Windows.Forms.Padding(0);
            this.btAddPcUser.UseDefaultRadiusAndThickness = true;
            this.btAddPcUser.Click += new System.EventHandler(this.btAddPcUser_Click);
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BackColor = System.Drawing.Color.White;
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.btFemale);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel3);
            this.bunifuGroupBox1.Controls.Add(this.rdbFemale);
            this.bunifuGroupBox1.Controls.Add(this.rdbMale);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(144, 113);
            this.bunifuGroupBox1.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuGroupBox1.Size = new System.Drawing.Size(281, 68);
            this.bunifuGroupBox1.TabIndex = 21;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Gender";
            // 
            // btFemale
            // 
            this.btFemale.AllowParentOverrides = false;
            this.btFemale.AutoEllipsis = false;
            this.btFemale.Cursor = System.Windows.Forms.Cursors.Default;
            this.btFemale.CursorType = System.Windows.Forms.Cursors.Default;
            this.btFemale.Font = new System.Drawing.Font("Poppins", 10.2F);
            this.btFemale.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btFemale.Location = new System.Drawing.Point(184, 27);
            this.btFemale.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.btFemale.Name = "btFemale";
            this.btFemale.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.btFemale.Size = new System.Drawing.Size(89, 42);
            this.btFemale.TabIndex = 23;
            this.btFemale.Text = "Female";
            this.btFemale.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.btFemale.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Poppins", 10.2F);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuLabel3.Location = new System.Drawing.Point(47, 27);
            this.bunifuLabel3.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(58, 42);
            this.bunifuLabel3.TabIndex = 22;
            this.bunifuLabel3.Text = "Male";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // rdbFemale
            // 
            this.rdbFemale.AllowBindingControlLocation = false;
            this.rdbFemale.BackColor = System.Drawing.Color.Transparent;
            this.rdbFemale.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.rdbFemale.BorderThickness = 1;
            this.rdbFemale.Checked = false;
            this.rdbFemale.Location = new System.Drawing.Point(160, 32);
            this.rdbFemale.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.rdbFemale.Name = "rdbFemale";
            this.rdbFemale.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.rdbFemale.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rdbFemale.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.rdbFemale.RadioColor = System.Drawing.Color.DodgerBlue;
            this.rdbFemale.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rdbFemale.Size = new System.Drawing.Size(20, 20);
            this.rdbFemale.TabIndex = 21;
            this.rdbFemale.Text = null;
            // 
            // rdbMale
            // 
            this.rdbMale.AllowBindingControlLocation = false;
            this.rdbMale.BackColor = System.Drawing.Color.Transparent;
            this.rdbMale.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.rdbMale.BorderThickness = 1;
            this.rdbMale.Checked = true;
            this.rdbMale.Location = new System.Drawing.Point(23, 32);
            this.rdbMale.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.rdbMale.Name = "rdbMale";
            this.rdbMale.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.rdbMale.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rdbMale.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.rdbMale.RadioColor = System.Drawing.Color.DodgerBlue;
            this.rdbMale.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rdbMale.Size = new System.Drawing.Size(20, 20);
            this.rdbMale.TabIndex = 20;
            this.rdbMale.Text = null;
            // 
            // pcUser
            // 
            this.pcUser.AllowFocused = false;
            this.pcUser.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pcUser.AutoSizeHeight = true;
            this.pcUser.BorderRadius = 0;
            this.pcUser.Image = ((System.Drawing.Image)(resources.GetObject("pcUser.Image")));
            this.pcUser.IsCircle = true;
            this.pcUser.Location = new System.Drawing.Point(17, 23);
            this.pcUser.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.pcUser.Name = "pcUser";
            this.pcUser.Size = new System.Drawing.Size(110, 110);
            this.pcUser.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pcUser.TabIndex = 18;
            this.pcUser.TabStop = false;
            this.pcUser.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // HireDate
            // 
            this.HireDate.BackColor = System.Drawing.Color.White;
            this.HireDate.BorderColor = System.Drawing.Color.Silver;
            this.HireDate.BorderRadius = 1;
            this.HireDate.Color = System.Drawing.Color.Silver;
            this.HireDate.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.HireDate.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Right;
            this.HireDate.DisabledColor = System.Drawing.Color.Gray;
            this.HireDate.DisplayWeekNumbers = false;
            this.HireDate.DPHeight = 0;
            this.HireDate.FillDatePicker = false;
            this.HireDate.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.HireDate.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.HireDate.Icon = ((System.Drawing.Image)(resources.GetObject("HireDate.Icon")));
            this.HireDate.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.HireDate.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Left;
            this.HireDate.LeftTextMargin = 30;
            this.HireDate.Location = new System.Drawing.Point(16, 441);
            this.HireDate.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.HireDate.MinimumSize = new System.Drawing.Size(4, 32);
            this.HireDate.Name = "HireDate";
            this.HireDate.Size = new System.Drawing.Size(710, 49);
            this.HireDate.TabIndex = 17;
            this.HireDate.Value = new System.DateTime(2025, 4, 14, 13, 5, 36, 0);
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel7.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.ForeColor = System.Drawing.SystemColors.Window;
            this.bunifuLabel7.Location = new System.Drawing.Point(17, 405);
            this.bunifuLabel7.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(119, 42);
            this.bunifuLabel7.TabIndex = 16;
            this.bunifuLabel7.Text = "Hire Date";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.SystemColors.Window;
            this.bunifuLabel6.Location = new System.Drawing.Point(387, 198);
            this.bunifuLabel6.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(124, 42);
            this.bunifuLabel6.TabIndex = 11;
            this.bunifuLabel6.Text = "Password";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.SystemColors.Window;
            this.bunifuLabel5.Location = new System.Drawing.Point(387, 302);
            this.bunifuLabel5.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(81, 42);
            this.bunifuLabel5.TabIndex = 9;
            this.bunifuLabel5.Text = "Phone";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btCanCel
            // 
            this.btCanCel.AllowAnimations = true;
            this.btCanCel.AllowMouseEffects = true;
            this.btCanCel.AllowToggling = false;
            this.btCanCel.AnimationSpeed = 200;
            this.btCanCel.AutoGenerateColors = false;
            this.btCanCel.AutoRoundBorders = false;
            this.btCanCel.AutoSizeLeftIcon = true;
            this.btCanCel.AutoSizeRightIcon = true;
            this.btCanCel.BackColor = System.Drawing.Color.Transparent;
            this.btCanCel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btCanCel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btCanCel.BackgroundImage")));
            this.btCanCel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btCanCel.ButtonText = "Cancel";
            this.btCanCel.ButtonTextMarginLeft = 0;
            this.btCanCel.ColorContrastOnClick = 45;
            this.btCanCel.ColorContrastOnHover = 45;
            this.btCanCel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btCanCel.CustomizableEdges = borderEdges11;
            this.btCanCel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btCanCel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btCanCel.DisabledFillColor = System.Drawing.Color.Empty;
            this.btCanCel.DisabledForecolor = System.Drawing.Color.Empty;
            this.btCanCel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btCanCel.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btCanCel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btCanCel.IconLeft = null;
            this.btCanCel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btCanCel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btCanCel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btCanCel.IconMarginLeft = 11;
            this.btCanCel.IconPadding = 10;
            this.btCanCel.IconRight = null;
            this.btCanCel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btCanCel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btCanCel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btCanCel.IconSize = 25;
            this.btCanCel.IdleBorderColor = System.Drawing.Color.Empty;
            this.btCanCel.IdleBorderRadius = 0;
            this.btCanCel.IdleBorderThickness = 0;
            this.btCanCel.IdleFillColor = System.Drawing.Color.Empty;
            this.btCanCel.IdleIconLeftImage = null;
            this.btCanCel.IdleIconRightImage = null;
            this.btCanCel.IndicateFocus = false;
            this.btCanCel.Location = new System.Drawing.Point(387, 551);
            this.btCanCel.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.btCanCel.Name = "btCanCel";
            this.btCanCel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btCanCel.OnDisabledState.BorderRadius = 1;
            this.btCanCel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btCanCel.OnDisabledState.BorderThickness = 1;
            this.btCanCel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btCanCel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btCanCel.OnDisabledState.IconLeftImage = null;
            this.btCanCel.OnDisabledState.IconRightImage = null;
            this.btCanCel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btCanCel.onHoverState.BorderRadius = 1;
            this.btCanCel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btCanCel.onHoverState.BorderThickness = 1;
            this.btCanCel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btCanCel.onHoverState.ForeColor = System.Drawing.Color.Transparent;
            this.btCanCel.onHoverState.IconLeftImage = null;
            this.btCanCel.onHoverState.IconRightImage = null;
            this.btCanCel.OnIdleState.BorderColor = System.Drawing.Color.MediumTurquoise;
            this.btCanCel.OnIdleState.BorderRadius = 1;
            this.btCanCel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btCanCel.OnIdleState.BorderThickness = 1;
            this.btCanCel.OnIdleState.FillColor = System.Drawing.Color.Azure;
            this.btCanCel.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btCanCel.OnIdleState.IconLeftImage = null;
            this.btCanCel.OnIdleState.IconRightImage = null;
            this.btCanCel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btCanCel.OnPressedState.BorderRadius = 1;
            this.btCanCel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btCanCel.OnPressedState.BorderThickness = 1;
            this.btCanCel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btCanCel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btCanCel.OnPressedState.IconLeftImage = null;
            this.btCanCel.OnPressedState.IconRightImage = null;
            this.btCanCel.Size = new System.Drawing.Size(164, 41);
            this.btCanCel.TabIndex = 7;
            this.btCanCel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btCanCel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btCanCel.TextMarginLeft = 0;
            this.btCanCel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btCanCel.UseDefaultRadiusAndThickness = true;
            this.btCanCel.Click += new System.EventHandler(this.btCancel_Click);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.SystemColors.Window;
            this.bunifuLabel4.Location = new System.Drawing.Point(17, 302);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(71, 42);
            this.bunifuLabel4.TabIndex = 6;
            this.bunifuLabel4.Text = "Email";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel13
            // 
            this.bunifuLabel13.AllowParentOverrides = false;
            this.bunifuLabel13.AutoEllipsis = false;
            this.bunifuLabel13.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel13.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel13.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel13.ForeColor = System.Drawing.SystemColors.Window;
            this.bunifuLabel13.Location = new System.Drawing.Point(16, 198);
            this.bunifuLabel13.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bunifuLabel13.Name = "bunifuLabel13";
            this.bunifuLabel13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel13.Size = new System.Drawing.Size(135, 42);
            this.bunifuLabel13.TabIndex = 1;
            this.bunifuLabel13.Text = "UserName";
            this.bunifuLabel13.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel13.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btAdd
            // 
            this.btAdd.AllowAnimations = true;
            this.btAdd.AllowMouseEffects = true;
            this.btAdd.AllowToggling = false;
            this.btAdd.AnimationSpeed = 200;
            this.btAdd.AutoGenerateColors = false;
            this.btAdd.AutoRoundBorders = false;
            this.btAdd.AutoSizeLeftIcon = true;
            this.btAdd.AutoSizeRightIcon = true;
            this.btAdd.BackColor = System.Drawing.Color.Transparent;
            this.btAdd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btAdd.BackgroundImage")));
            this.btAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAdd.ButtonText = "Add";
            this.btAdd.ButtonTextMarginLeft = 0;
            this.btAdd.ColorContrastOnClick = 45;
            this.btAdd.ColorContrastOnHover = 45;
            this.btAdd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btAdd.CustomizableEdges = borderEdges12;
            this.btAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btAdd.DisabledFillColor = System.Drawing.Color.Empty;
            this.btAdd.DisabledForecolor = System.Drawing.Color.Empty;
            this.btAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btAdd.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btAdd.IconLeft = null;
            this.btAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btAdd.IconMarginLeft = 11;
            this.btAdd.IconPadding = 10;
            this.btAdd.IconRight = null;
            this.btAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btAdd.IconSize = 25;
            this.btAdd.IdleBorderColor = System.Drawing.Color.Empty;
            this.btAdd.IdleBorderRadius = 0;
            this.btAdd.IdleBorderThickness = 0;
            this.btAdd.IdleFillColor = System.Drawing.Color.Empty;
            this.btAdd.IdleIconLeftImage = null;
            this.btAdd.IdleIconRightImage = null;
            this.btAdd.IndicateFocus = false;
            this.btAdd.Location = new System.Drawing.Point(192, 551);
            this.btAdd.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.btAdd.Name = "btAdd";
            this.btAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAdd.OnDisabledState.BorderRadius = 1;
            this.btAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAdd.OnDisabledState.BorderThickness = 1;
            this.btAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAdd.OnDisabledState.IconLeftImage = null;
            this.btAdd.OnDisabledState.IconRightImage = null;
            this.btAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAdd.onHoverState.BorderRadius = 1;
            this.btAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAdd.onHoverState.BorderThickness = 1;
            this.btAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAdd.onHoverState.ForeColor = System.Drawing.Color.Transparent;
            this.btAdd.onHoverState.IconLeftImage = null;
            this.btAdd.onHoverState.IconRightImage = null;
            this.btAdd.OnIdleState.BorderColor = System.Drawing.Color.MediumTurquoise;
            this.btAdd.OnIdleState.BorderRadius = 1;
            this.btAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAdd.OnIdleState.BorderThickness = 1;
            this.btAdd.OnIdleState.FillColor = System.Drawing.Color.Azure;
            this.btAdd.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.btAdd.OnIdleState.IconLeftImage = null;
            this.btAdd.OnIdleState.IconRightImage = null;
            this.btAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAdd.OnPressedState.BorderRadius = 1;
            this.btAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAdd.OnPressedState.BorderThickness = 1;
            this.btAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.btAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btAdd.OnPressedState.IconLeftImage = null;
            this.btAdd.OnPressedState.IconRightImage = null;
            this.btAdd.Size = new System.Drawing.Size(164, 41);
            this.btAdd.TabIndex = 2;
            this.btAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btAdd.TextMarginLeft = 0;
            this.btAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btAdd.UseDefaultRadiusAndThickness = true;
            this.btAdd.Click += new System.EventHandler(this.btAdd_Click);
            // 
            // lbForm
            // 
            this.lbForm.AllowParentOverrides = false;
            this.lbForm.AutoEllipsis = false;
            this.lbForm.BackColor = System.Drawing.Color.White;
            this.lbForm.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbForm.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbForm.Font = new System.Drawing.Font("Poppins Medium", 18F, System.Drawing.FontStyle.Bold);
            this.lbForm.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.lbForm.Location = new System.Drawing.Point(270, 28);
            this.lbForm.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.lbForm.Name = "lbForm";
            this.lbForm.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbForm.Size = new System.Drawing.Size(303, 75);
            this.lbForm.TabIndex = 4;
            this.lbForm.Text = "Add New User";
            this.lbForm.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lbForm.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // AddUserForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(16F, 42F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FloralWhite;
            this.ClientSize = new System.Drawing.Size(765, 746);
            this.Controls.Add(this.lbForm);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuPanel1);
            this.Font = new System.Drawing.Font("Poppins Medium", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.MaximizeBox = false;
            this.Name = "AddUserForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "AddUserForm";
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pcUser)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox tbFirstName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btAddPcUser;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuLabel btFemale;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuRadioButton rdbFemale;
        private Bunifu.UI.WinForms.BunifuRadioButton rdbMale;
        private Bunifu.UI.WinForms.BunifuPictureBox pcUser;
        private Bunifu.UI.WinForms.BunifuDatePicker HireDate;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btCanCel;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btAdd;
        private Bunifu.UI.WinForms.BunifuLabel lbForm;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel12;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel15;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel14;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel13;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private System.Windows.Forms.ComboBox cbUserRole;
        private Bunifu.UI.WinForms.BunifuTextBox tbLastName;
        private Bunifu.UI.WinForms.BunifuTextBox tbPhone;
        private Bunifu.UI.WinForms.BunifuTextBox tbEmail;
        private Bunifu.UI.WinForms.BunifuTextBox tbPassword;
        private Bunifu.UI.WinForms.BunifuTextBox tbLogin;
    }
}