namespace GUI
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.stockViewBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn_SignOut = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.User_FullName = new Bunifu.UI.WinForms.BunifuLabel();
            this.avatar = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.statsViewBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.promotionViewBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.employeeViewBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.categoryViewBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.productViewBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.avatar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel3
            // 
            this.bunifuPanel3.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
            this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BorderRadius = 3;
            this.bunifuPanel3.BorderThickness = 1;
            this.bunifuPanel3.Location = new System.Drawing.Point(264, 2);
            this.bunifuPanel3.Name = "bunifuPanel3";
            this.bunifuPanel3.ShowBorders = true;
            this.bunifuPanel3.Size = new System.Drawing.Size(1291, 847);
            this.bunifuPanel3.TabIndex = 5;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 0;
            this.bunifuPanel2.Controls.Add(this.stockViewBtn);
            this.bunifuPanel2.Controls.Add(this.btn_SignOut);
            this.bunifuPanel2.Controls.Add(this.User_FullName);
            this.bunifuPanel2.Controls.Add(this.avatar);
            this.bunifuPanel2.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel2.Controls.Add(this.bunifuPictureBox1);
            this.bunifuPanel2.Controls.Add(this.statsViewBtn);
            this.bunifuPanel2.Controls.Add(this.promotionViewBtn);
            this.bunifuPanel2.Controls.Add(this.employeeViewBtn);
            this.bunifuPanel2.Controls.Add(this.categoryViewBtn);
            this.bunifuPanel2.Controls.Add(this.productViewBtn);
            this.bunifuPanel2.Location = new System.Drawing.Point(-1, 2);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(264, 848);
            this.bunifuPanel2.TabIndex = 4;
            // 
            // stockViewBtn
            // 
            this.stockViewBtn.AllowAnimations = true;
            this.stockViewBtn.AllowMouseEffects = true;
            this.stockViewBtn.AllowToggling = false;
            this.stockViewBtn.AnimationSpeed = 1;
            this.stockViewBtn.AutoGenerateColors = false;
            this.stockViewBtn.AutoRoundBorders = true;
            this.stockViewBtn.AutoSizeLeftIcon = true;
            this.stockViewBtn.AutoSizeRightIcon = true;
            this.stockViewBtn.BackColor = System.Drawing.Color.Transparent;
            this.stockViewBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.stockViewBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("stockViewBtn.BackgroundImage")));
            this.stockViewBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.stockViewBtn.ButtonText = "Stock Management";
            this.stockViewBtn.ButtonTextMarginLeft = 0;
            this.stockViewBtn.ColorContrastOnClick = 45;
            this.stockViewBtn.ColorContrastOnHover = 45;
            this.stockViewBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.stockViewBtn.CustomizableEdges = borderEdges1;
            this.stockViewBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.stockViewBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.stockViewBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.stockViewBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.stockViewBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.stockViewBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.stockViewBtn.ForeColor = System.Drawing.Color.White;
            this.stockViewBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.stockViewBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.stockViewBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.stockViewBtn.IconMarginLeft = 11;
            this.stockViewBtn.IconPadding = 10;
            this.stockViewBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.stockViewBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.stockViewBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.stockViewBtn.IconSize = 25;
            this.stockViewBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.stockViewBtn.IdleBorderRadius = 41;
            this.stockViewBtn.IdleBorderThickness = 1;
            this.stockViewBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.stockViewBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("stockViewBtn.IdleIconLeftImage")));
            this.stockViewBtn.IdleIconRightImage = null;
            this.stockViewBtn.IndicateFocus = false;
            this.stockViewBtn.Location = new System.Drawing.Point(3, 318);
            this.stockViewBtn.Name = "stockViewBtn";
            this.stockViewBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.stockViewBtn.OnDisabledState.BorderRadius = 1;
            this.stockViewBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.stockViewBtn.OnDisabledState.BorderThickness = 1;
            this.stockViewBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.stockViewBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.stockViewBtn.OnDisabledState.IconLeftImage = null;
            this.stockViewBtn.OnDisabledState.IconRightImage = null;
            this.stockViewBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.stockViewBtn.onHoverState.BorderRadius = 1;
            this.stockViewBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.stockViewBtn.onHoverState.BorderThickness = 1;
            this.stockViewBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.stockViewBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.stockViewBtn.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage")));
            this.stockViewBtn.onHoverState.IconRightImage = null;
            this.stockViewBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.stockViewBtn.OnIdleState.BorderRadius = 1;
            this.stockViewBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.stockViewBtn.OnIdleState.BorderThickness = 1;
            this.stockViewBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.stockViewBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.stockViewBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("stockViewBtn.OnIdleState.IconLeftImage")));
            this.stockViewBtn.OnIdleState.IconRightImage = null;
            this.stockViewBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.stockViewBtn.OnPressedState.BorderRadius = 1;
            this.stockViewBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.stockViewBtn.OnPressedState.BorderThickness = 1;
            this.stockViewBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.stockViewBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.stockViewBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage1")));
            this.stockViewBtn.OnPressedState.IconRightImage = null;
            this.stockViewBtn.Size = new System.Drawing.Size(261, 43);
            this.stockViewBtn.TabIndex = 4;
            this.stockViewBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.stockViewBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.stockViewBtn.TextMarginLeft = 0;
            this.stockViewBtn.TextPadding = new System.Windows.Forms.Padding(35, 2, 0, 0);
            this.stockViewBtn.UseDefaultRadiusAndThickness = true;
            this.stockViewBtn.Click += new System.EventHandler(this.stockViewBtn_Click);
            // 
            // btn_SignOut
            // 
            this.btn_SignOut.AllowAnimations = true;
            this.btn_SignOut.AllowMouseEffects = true;
            this.btn_SignOut.AllowToggling = false;
            this.btn_SignOut.AnimationSpeed = 1;
            this.btn_SignOut.AutoGenerateColors = false;
            this.btn_SignOut.AutoRoundBorders = true;
            this.btn_SignOut.AutoSizeLeftIcon = true;
            this.btn_SignOut.AutoSizeRightIcon = true;
            this.btn_SignOut.BackColor = System.Drawing.Color.Transparent;
            this.btn_SignOut.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.btn_SignOut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_SignOut.BackgroundImage")));
            this.btn_SignOut.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.btn_SignOut.ButtonText = "Sign out";
            this.btn_SignOut.ButtonTextMarginLeft = 0;
            this.btn_SignOut.ColorContrastOnClick = 45;
            this.btn_SignOut.ColorContrastOnHover = 45;
            this.btn_SignOut.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_SignOut.CustomizableEdges = borderEdges2;
            this.btn_SignOut.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_SignOut.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_SignOut.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SignOut.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SignOut.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn_SignOut.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_SignOut.ForeColor = System.Drawing.Color.White;
            this.btn_SignOut.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_SignOut.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_SignOut.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_SignOut.IconMarginLeft = 11;
            this.btn_SignOut.IconPadding = 10;
            this.btn_SignOut.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_SignOut.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_SignOut.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_SignOut.IconSize = 25;
            this.btn_SignOut.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.btn_SignOut.IdleBorderRadius = 41;
            this.btn_SignOut.IdleBorderThickness = 1;
            this.btn_SignOut.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.btn_SignOut.IdleIconLeftImage = global::GUI.Properties.Resources.sign_out_white;
            this.btn_SignOut.IdleIconRightImage = null;
            this.btn_SignOut.IndicateFocus = false;
            this.btn_SignOut.Location = new System.Drawing.Point(3, 760);
            this.btn_SignOut.Name = "btn_SignOut";
            this.btn_SignOut.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_SignOut.OnDisabledState.BorderRadius = 1;
            this.btn_SignOut.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_SignOut.OnDisabledState.BorderThickness = 1;
            this.btn_SignOut.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SignOut.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SignOut.OnDisabledState.IconLeftImage = null;
            this.btn_SignOut.OnDisabledState.IconRightImage = null;
            this.btn_SignOut.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btn_SignOut.onHoverState.BorderRadius = 1;
            this.btn_SignOut.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_SignOut.onHoverState.BorderThickness = 1;
            this.btn_SignOut.onHoverState.FillColor = System.Drawing.Color.White;
            this.btn_SignOut.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btn_SignOut.onHoverState.IconLeftImage = global::GUI.Properties.Resources.sign_out_black;
            this.btn_SignOut.onHoverState.IconRightImage = null;
            this.btn_SignOut.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.btn_SignOut.OnIdleState.BorderRadius = 1;
            this.btn_SignOut.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.btn_SignOut.OnIdleState.BorderThickness = 1;
            this.btn_SignOut.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.btn_SignOut.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_SignOut.OnIdleState.IconLeftImage = global::GUI.Properties.Resources.sign_out_white;
            this.btn_SignOut.OnIdleState.IconRightImage = null;
            this.btn_SignOut.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btn_SignOut.OnPressedState.BorderRadius = 1;
            this.btn_SignOut.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_SignOut.OnPressedState.BorderThickness = 1;
            this.btn_SignOut.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btn_SignOut.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btn_SignOut.OnPressedState.IconLeftImage = global::GUI.Properties.Resources.employee_man_black;
            this.btn_SignOut.OnPressedState.IconRightImage = null;
            this.btn_SignOut.Size = new System.Drawing.Size(261, 43);
            this.btn_SignOut.TabIndex = 8;
            this.btn_SignOut.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_SignOut.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_SignOut.TextMarginLeft = 0;
            this.btn_SignOut.TextPadding = new System.Windows.Forms.Padding(35, 2, 0, 0);
            this.btn_SignOut.UseDefaultRadiusAndThickness = true;
            this.btn_SignOut.Click += new System.EventHandler(this.btn_SignOut_Click);
            // 
            // User_FullName
            // 
            this.User_FullName.AllowParentOverrides = false;
            this.User_FullName.AutoEllipsis = false;
            this.User_FullName.AutoSize = false;
            this.User_FullName.Cursor = System.Windows.Forms.Cursors.Default;
            this.User_FullName.CursorType = System.Windows.Forms.Cursors.Default;
            this.User_FullName.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.User_FullName.ForeColor = System.Drawing.Color.White;
            this.User_FullName.Location = new System.Drawing.Point(77, 699);
            this.User_FullName.Name = "User_FullName";
            this.User_FullName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.User_FullName.Size = new System.Drawing.Size(123, 40);
            this.User_FullName.TabIndex = 1;
            this.User_FullName.Text = "User";
            this.User_FullName.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.User_FullName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // avatar
            // 
            this.avatar.AllowFocused = false;
            this.avatar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.avatar.AutoSizeHeight = true;
            this.avatar.BorderRadius = 24;
            this.avatar.Image = ((System.Drawing.Image)(resources.GetObject("avatar.Image")));
            this.avatar.IsCircle = true;
            this.avatar.Location = new System.Drawing.Point(13, 705);
            this.avatar.Name = "avatar";
            this.avatar.Size = new System.Drawing.Size(49, 49);
            this.avatar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.avatar.TabIndex = 7;
            this.avatar.TabStop = false;
            this.avatar.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(85, 31);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(158, 36);
            this.bunifuLabel2.TabIndex = 1;
            this.bunifuLabel2.Text = "WPN Shop";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 33;
            this.bunifuPictureBox1.Image = global::GUI.Properties.Resources.Black_and_White_Modern_Shoes_Store_Logo__1_;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(13, 33);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(66, 66);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // statsViewBtn
            // 
            this.statsViewBtn.AllowAnimations = true;
            this.statsViewBtn.AllowMouseEffects = true;
            this.statsViewBtn.AllowToggling = false;
            this.statsViewBtn.AnimationSpeed = 1;
            this.statsViewBtn.AutoGenerateColors = false;
            this.statsViewBtn.AutoRoundBorders = true;
            this.statsViewBtn.AutoSizeLeftIcon = true;
            this.statsViewBtn.AutoSizeRightIcon = true;
            this.statsViewBtn.BackColor = System.Drawing.Color.Transparent;
            this.statsViewBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.statsViewBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("statsViewBtn.BackgroundImage")));
            this.statsViewBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.statsViewBtn.ButtonText = "Statistics Reports";
            this.statsViewBtn.ButtonTextMarginLeft = 0;
            this.statsViewBtn.ColorContrastOnClick = 45;
            this.statsViewBtn.ColorContrastOnHover = 45;
            this.statsViewBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.statsViewBtn.CustomizableEdges = borderEdges3;
            this.statsViewBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.statsViewBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.statsViewBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.statsViewBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.statsViewBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.statsViewBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.statsViewBtn.ForeColor = System.Drawing.Color.White;
            this.statsViewBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.statsViewBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.statsViewBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.statsViewBtn.IconMarginLeft = 11;
            this.statsViewBtn.IconPadding = 10;
            this.statsViewBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.statsViewBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.statsViewBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.statsViewBtn.IconSize = 25;
            this.statsViewBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.statsViewBtn.IdleBorderRadius = 41;
            this.statsViewBtn.IdleBorderThickness = 1;
            this.statsViewBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.statsViewBtn.IdleIconLeftImage = global::GUI.Properties.Resources.chart_histogram_white;
            this.statsViewBtn.IdleIconRightImage = null;
            this.statsViewBtn.IndicateFocus = false;
            this.statsViewBtn.Location = new System.Drawing.Point(1, 546);
            this.statsViewBtn.Name = "statsViewBtn";
            this.statsViewBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.statsViewBtn.OnDisabledState.BorderRadius = 1;
            this.statsViewBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.statsViewBtn.OnDisabledState.BorderThickness = 1;
            this.statsViewBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.statsViewBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.statsViewBtn.OnDisabledState.IconLeftImage = null;
            this.statsViewBtn.OnDisabledState.IconRightImage = null;
            this.statsViewBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.statsViewBtn.onHoverState.BorderRadius = 1;
            this.statsViewBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.statsViewBtn.onHoverState.BorderThickness = 1;
            this.statsViewBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.statsViewBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.statsViewBtn.onHoverState.IconLeftImage = global::GUI.Properties.Resources.chart_histogram;
            this.statsViewBtn.onHoverState.IconRightImage = null;
            this.statsViewBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.statsViewBtn.OnIdleState.BorderRadius = 1;
            this.statsViewBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.statsViewBtn.OnIdleState.BorderThickness = 1;
            this.statsViewBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.statsViewBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.statsViewBtn.OnIdleState.IconLeftImage = global::GUI.Properties.Resources.chart_histogram_white;
            this.statsViewBtn.OnIdleState.IconRightImage = null;
            this.statsViewBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.statsViewBtn.OnPressedState.BorderRadius = 1;
            this.statsViewBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.statsViewBtn.OnPressedState.BorderThickness = 1;
            this.statsViewBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.statsViewBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.statsViewBtn.OnPressedState.IconLeftImage = global::GUI.Properties.Resources.chart_histogram;
            this.statsViewBtn.OnPressedState.IconRightImage = null;
            this.statsViewBtn.Size = new System.Drawing.Size(261, 43);
            this.statsViewBtn.TabIndex = 6;
            this.statsViewBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.statsViewBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.statsViewBtn.TextMarginLeft = 0;
            this.statsViewBtn.TextPadding = new System.Windows.Forms.Padding(35, 2, 0, 0);
            this.statsViewBtn.UseDefaultRadiusAndThickness = true;
            this.statsViewBtn.Click += new System.EventHandler(this.statsViewBtn_Click);
            // 
            // promotionViewBtn
            // 
            this.promotionViewBtn.AllowAnimations = true;
            this.promotionViewBtn.AllowMouseEffects = true;
            this.promotionViewBtn.AllowToggling = false;
            this.promotionViewBtn.AnimationSpeed = 1;
            this.promotionViewBtn.AutoGenerateColors = false;
            this.promotionViewBtn.AutoRoundBorders = true;
            this.promotionViewBtn.AutoSizeLeftIcon = true;
            this.promotionViewBtn.AutoSizeRightIcon = true;
            this.promotionViewBtn.BackColor = System.Drawing.Color.Transparent;
            this.promotionViewBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.promotionViewBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("promotionViewBtn.BackgroundImage")));
            this.promotionViewBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.promotionViewBtn.ButtonText = "Promotion";
            this.promotionViewBtn.ButtonTextMarginLeft = 0;
            this.promotionViewBtn.ColorContrastOnClick = 45;
            this.promotionViewBtn.ColorContrastOnHover = 45;
            this.promotionViewBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.promotionViewBtn.CustomizableEdges = borderEdges4;
            this.promotionViewBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.promotionViewBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.promotionViewBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.promotionViewBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.promotionViewBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.promotionViewBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.promotionViewBtn.ForeColor = System.Drawing.Color.White;
            this.promotionViewBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.promotionViewBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.promotionViewBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.promotionViewBtn.IconMarginLeft = 11;
            this.promotionViewBtn.IconPadding = 10;
            this.promotionViewBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.promotionViewBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.promotionViewBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.promotionViewBtn.IconSize = 25;
            this.promotionViewBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.promotionViewBtn.IdleBorderRadius = 41;
            this.promotionViewBtn.IdleBorderThickness = 1;
            this.promotionViewBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.promotionViewBtn.IdleIconLeftImage = global::GUI.Properties.Resources.gift_white;
            this.promotionViewBtn.IdleIconRightImage = null;
            this.promotionViewBtn.IndicateFocus = false;
            this.promotionViewBtn.Location = new System.Drawing.Point(0, 466);
            this.promotionViewBtn.Name = "promotionViewBtn";
            this.promotionViewBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.promotionViewBtn.OnDisabledState.BorderRadius = 1;
            this.promotionViewBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.promotionViewBtn.OnDisabledState.BorderThickness = 1;
            this.promotionViewBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.promotionViewBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.promotionViewBtn.OnDisabledState.IconLeftImage = null;
            this.promotionViewBtn.OnDisabledState.IconRightImage = null;
            this.promotionViewBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.promotionViewBtn.onHoverState.BorderRadius = 1;
            this.promotionViewBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.promotionViewBtn.onHoverState.BorderThickness = 1;
            this.promotionViewBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.promotionViewBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.promotionViewBtn.onHoverState.IconLeftImage = global::GUI.Properties.Resources.gift;
            this.promotionViewBtn.onHoverState.IconRightImage = null;
            this.promotionViewBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.promotionViewBtn.OnIdleState.BorderRadius = 1;
            this.promotionViewBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.promotionViewBtn.OnIdleState.BorderThickness = 1;
            this.promotionViewBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.promotionViewBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.promotionViewBtn.OnIdleState.IconLeftImage = global::GUI.Properties.Resources.gift_white;
            this.promotionViewBtn.OnIdleState.IconRightImage = null;
            this.promotionViewBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.promotionViewBtn.OnPressedState.BorderRadius = 1;
            this.promotionViewBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.promotionViewBtn.OnPressedState.BorderThickness = 1;
            this.promotionViewBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.promotionViewBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.promotionViewBtn.OnPressedState.IconLeftImage = global::GUI.Properties.Resources.gift;
            this.promotionViewBtn.OnPressedState.IconRightImage = null;
            this.promotionViewBtn.Size = new System.Drawing.Size(261, 43);
            this.promotionViewBtn.TabIndex = 5;
            this.promotionViewBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.promotionViewBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.promotionViewBtn.TextMarginLeft = 0;
            this.promotionViewBtn.TextPadding = new System.Windows.Forms.Padding(35, 2, 0, 0);
            this.promotionViewBtn.UseDefaultRadiusAndThickness = true;
            this.promotionViewBtn.Click += new System.EventHandler(this.promotionViewBtn_Click);
            // 
            // employeeViewBtn
            // 
            this.employeeViewBtn.AllowAnimations = true;
            this.employeeViewBtn.AllowMouseEffects = true;
            this.employeeViewBtn.AllowToggling = false;
            this.employeeViewBtn.AnimationSpeed = 1;
            this.employeeViewBtn.AutoGenerateColors = false;
            this.employeeViewBtn.AutoRoundBorders = true;
            this.employeeViewBtn.AutoSizeLeftIcon = true;
            this.employeeViewBtn.AutoSizeRightIcon = true;
            this.employeeViewBtn.BackColor = System.Drawing.Color.Transparent;
            this.employeeViewBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.employeeViewBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("employeeViewBtn.BackgroundImage")));
            this.employeeViewBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.employeeViewBtn.ButtonText = "Employee Management";
            this.employeeViewBtn.ButtonTextMarginLeft = 0;
            this.employeeViewBtn.ColorContrastOnClick = 45;
            this.employeeViewBtn.ColorContrastOnHover = 45;
            this.employeeViewBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.employeeViewBtn.CustomizableEdges = borderEdges5;
            this.employeeViewBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.employeeViewBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.employeeViewBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.employeeViewBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.employeeViewBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.employeeViewBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.employeeViewBtn.ForeColor = System.Drawing.Color.White;
            this.employeeViewBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.employeeViewBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.employeeViewBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.employeeViewBtn.IconMarginLeft = 11;
            this.employeeViewBtn.IconPadding = 10;
            this.employeeViewBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.employeeViewBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.employeeViewBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.employeeViewBtn.IconSize = 25;
            this.employeeViewBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.employeeViewBtn.IdleBorderRadius = 41;
            this.employeeViewBtn.IdleBorderThickness = 1;
            this.employeeViewBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.employeeViewBtn.IdleIconLeftImage = global::GUI.Properties.Resources.employee_man_white;
            this.employeeViewBtn.IdleIconRightImage = null;
            this.employeeViewBtn.IndicateFocus = false;
            this.employeeViewBtn.Location = new System.Drawing.Point(0, 385);
            this.employeeViewBtn.Name = "employeeViewBtn";
            this.employeeViewBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.employeeViewBtn.OnDisabledState.BorderRadius = 1;
            this.employeeViewBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.employeeViewBtn.OnDisabledState.BorderThickness = 1;
            this.employeeViewBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.employeeViewBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.employeeViewBtn.OnDisabledState.IconLeftImage = null;
            this.employeeViewBtn.OnDisabledState.IconRightImage = null;
            this.employeeViewBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.employeeViewBtn.onHoverState.BorderRadius = 1;
            this.employeeViewBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.employeeViewBtn.onHoverState.BorderThickness = 1;
            this.employeeViewBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.employeeViewBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.employeeViewBtn.onHoverState.IconLeftImage = global::GUI.Properties.Resources.employee_man_black;
            this.employeeViewBtn.onHoverState.IconRightImage = null;
            this.employeeViewBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.employeeViewBtn.OnIdleState.BorderRadius = 1;
            this.employeeViewBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.employeeViewBtn.OnIdleState.BorderThickness = 1;
            this.employeeViewBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.employeeViewBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.employeeViewBtn.OnIdleState.IconLeftImage = global::GUI.Properties.Resources.employee_man_white;
            this.employeeViewBtn.OnIdleState.IconRightImage = null;
            this.employeeViewBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.employeeViewBtn.OnPressedState.BorderRadius = 1;
            this.employeeViewBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.employeeViewBtn.OnPressedState.BorderThickness = 1;
            this.employeeViewBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.employeeViewBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.employeeViewBtn.OnPressedState.IconLeftImage = global::GUI.Properties.Resources.employee_man_black;
            this.employeeViewBtn.OnPressedState.IconRightImage = null;
            this.employeeViewBtn.Size = new System.Drawing.Size(261, 43);
            this.employeeViewBtn.TabIndex = 4;
            this.employeeViewBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.employeeViewBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.employeeViewBtn.TextMarginLeft = 0;
            this.employeeViewBtn.TextPadding = new System.Windows.Forms.Padding(35, 2, 0, 0);
            this.employeeViewBtn.UseDefaultRadiusAndThickness = true;
            this.employeeViewBtn.Click += new System.EventHandler(this.employeeViewBtn_Click);
            // 
            // categoryViewBtn
            // 
            this.categoryViewBtn.AllowAnimations = true;
            this.categoryViewBtn.AllowMouseEffects = true;
            this.categoryViewBtn.AllowToggling = false;
            this.categoryViewBtn.AnimationSpeed = 1;
            this.categoryViewBtn.AutoGenerateColors = false;
            this.categoryViewBtn.AutoRoundBorders = true;
            this.categoryViewBtn.AutoSizeLeftIcon = true;
            this.categoryViewBtn.AutoSizeRightIcon = true;
            this.categoryViewBtn.BackColor = System.Drawing.Color.Transparent;
            this.categoryViewBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.categoryViewBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("categoryViewBtn.BackgroundImage")));
            this.categoryViewBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.categoryViewBtn.ButtonText = "Category Management";
            this.categoryViewBtn.ButtonTextMarginLeft = 0;
            this.categoryViewBtn.ColorContrastOnClick = 45;
            this.categoryViewBtn.ColorContrastOnHover = 45;
            this.categoryViewBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.categoryViewBtn.CustomizableEdges = borderEdges6;
            this.categoryViewBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.categoryViewBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.categoryViewBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categoryViewBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.categoryViewBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.categoryViewBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.categoryViewBtn.ForeColor = System.Drawing.Color.White;
            this.categoryViewBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.categoryViewBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.categoryViewBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.categoryViewBtn.IconMarginLeft = 11;
            this.categoryViewBtn.IconPadding = 10;
            this.categoryViewBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.categoryViewBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.categoryViewBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.categoryViewBtn.IconSize = 25;
            this.categoryViewBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.categoryViewBtn.IdleBorderRadius = 41;
            this.categoryViewBtn.IdleBorderThickness = 1;
            this.categoryViewBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.categoryViewBtn.IdleIconLeftImage = global::GUI.Properties.Resources.tags__1_;
            this.categoryViewBtn.IdleIconRightImage = null;
            this.categoryViewBtn.IndicateFocus = false;
            this.categoryViewBtn.Location = new System.Drawing.Point(3, 247);
            this.categoryViewBtn.Name = "categoryViewBtn";
            this.categoryViewBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.categoryViewBtn.OnDisabledState.BorderRadius = 1;
            this.categoryViewBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoryViewBtn.OnDisabledState.BorderThickness = 1;
            this.categoryViewBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.categoryViewBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.categoryViewBtn.OnDisabledState.IconLeftImage = null;
            this.categoryViewBtn.OnDisabledState.IconRightImage = null;
            this.categoryViewBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.categoryViewBtn.onHoverState.BorderRadius = 1;
            this.categoryViewBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoryViewBtn.onHoverState.BorderThickness = 1;
            this.categoryViewBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.categoryViewBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.categoryViewBtn.onHoverState.IconLeftImage = global::GUI.Properties.Resources.tags;
            this.categoryViewBtn.onHoverState.IconRightImage = null;
            this.categoryViewBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.categoryViewBtn.OnIdleState.BorderRadius = 1;
            this.categoryViewBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.categoryViewBtn.OnIdleState.BorderThickness = 1;
            this.categoryViewBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.categoryViewBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.categoryViewBtn.OnIdleState.IconLeftImage = global::GUI.Properties.Resources.tags__1_;
            this.categoryViewBtn.OnIdleState.IconRightImage = null;
            this.categoryViewBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.categoryViewBtn.OnPressedState.BorderRadius = 1;
            this.categoryViewBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.categoryViewBtn.OnPressedState.BorderThickness = 1;
            this.categoryViewBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.categoryViewBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.categoryViewBtn.OnPressedState.IconLeftImage = global::GUI.Properties.Resources.tags;
            this.categoryViewBtn.OnPressedState.IconRightImage = null;
            this.categoryViewBtn.Size = new System.Drawing.Size(261, 43);
            this.categoryViewBtn.TabIndex = 3;
            this.categoryViewBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.categoryViewBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.categoryViewBtn.TextMarginLeft = 0;
            this.categoryViewBtn.TextPadding = new System.Windows.Forms.Padding(35, 2, 0, 0);
            this.categoryViewBtn.UseDefaultRadiusAndThickness = true;
            this.categoryViewBtn.Click += new System.EventHandler(this.categoryViewBtn_Click);
            // 
            // productViewBtn
            // 
            this.productViewBtn.AllowAnimations = true;
            this.productViewBtn.AllowMouseEffects = true;
            this.productViewBtn.AllowToggling = false;
            this.productViewBtn.AnimationSpeed = 1;
            this.productViewBtn.AutoGenerateColors = false;
            this.productViewBtn.AutoRoundBorders = true;
            this.productViewBtn.AutoSizeLeftIcon = true;
            this.productViewBtn.AutoSizeRightIcon = true;
            this.productViewBtn.BackColor = System.Drawing.Color.Transparent;
            this.productViewBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.productViewBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productViewBtn.BackgroundImage")));
            this.productViewBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.productViewBtn.ButtonText = "Product Management";
            this.productViewBtn.ButtonTextMarginLeft = 0;
            this.productViewBtn.ColorContrastOnClick = 45;
            this.productViewBtn.ColorContrastOnHover = 45;
            this.productViewBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.productViewBtn.CustomizableEdges = borderEdges7;
            this.productViewBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.productViewBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productViewBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productViewBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productViewBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.productViewBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.productViewBtn.ForeColor = System.Drawing.Color.White;
            this.productViewBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.productViewBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.productViewBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.productViewBtn.IconMarginLeft = 11;
            this.productViewBtn.IconPadding = 10;
            this.productViewBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.productViewBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.productViewBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.productViewBtn.IconSize = 25;
            this.productViewBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.productViewBtn.IdleBorderRadius = 41;
            this.productViewBtn.IdleBorderThickness = 1;
            this.productViewBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.productViewBtn.IdleIconLeftImage = global::GUI.Properties.Resources.cube_white;
            this.productViewBtn.IdleIconRightImage = null;
            this.productViewBtn.IndicateFocus = false;
            this.productViewBtn.Location = new System.Drawing.Point(2, 168);
            this.productViewBtn.Name = "productViewBtn";
            this.productViewBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productViewBtn.OnDisabledState.BorderRadius = 1;
            this.productViewBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.productViewBtn.OnDisabledState.BorderThickness = 1;
            this.productViewBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productViewBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productViewBtn.OnDisabledState.IconLeftImage = null;
            this.productViewBtn.OnDisabledState.IconRightImage = null;
            this.productViewBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.productViewBtn.onHoverState.BorderRadius = 1;
            this.productViewBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.productViewBtn.onHoverState.BorderThickness = 1;
            this.productViewBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.productViewBtn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.productViewBtn.onHoverState.IconLeftImage = global::GUI.Properties.Resources.cube_black;
            this.productViewBtn.onHoverState.IconRightImage = null;
            this.productViewBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.productViewBtn.OnIdleState.BorderRadius = 1;
            this.productViewBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.productViewBtn.OnIdleState.BorderThickness = 1;
            this.productViewBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(124)))), ((int)(((byte)(170)))), ((int)(((byte)(150)))));
            this.productViewBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.productViewBtn.OnIdleState.IconLeftImage = global::GUI.Properties.Resources.cube_white;
            this.productViewBtn.OnIdleState.IconRightImage = null;
            this.productViewBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.productViewBtn.OnPressedState.BorderRadius = 1;
            this.productViewBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.productViewBtn.OnPressedState.BorderThickness = 1;
            this.productViewBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.productViewBtn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.productViewBtn.OnPressedState.IconLeftImage = global::GUI.Properties.Resources.cube_black;
            this.productViewBtn.OnPressedState.IconRightImage = null;
            this.productViewBtn.Size = new System.Drawing.Size(261, 43);
            this.productViewBtn.TabIndex = 2;
            this.productViewBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.productViewBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.productViewBtn.TextMarginLeft = 0;
            this.productViewBtn.TextPadding = new System.Windows.Forms.Padding(35, 2, 0, 0);
            this.productViewBtn.UseDefaultRadiusAndThickness = true;
            this.productViewBtn.Click += new System.EventHandler(this.productViewBtn_Click);
            // 
            // MainForm
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.ClientSize = new System.Drawing.Size(1555, 850);
            this.Controls.Add(this.bunifuPanel3);
            this.Controls.Add(this.bunifuPanel2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.IsMdiContainer = true;
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MainForm";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.avatar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        //private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 promotionViewBtn;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 employeeViewBtn;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 categoryViewBtn;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 productViewBtn;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 statsViewBtn;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel User_FullName;
        private Bunifu.UI.WinForms.BunifuPictureBox avatar;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_SignOut;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 stockViewBtn;
    }
}
