namespace GUI
{
    partial class ProductManagement
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ProductManagement));
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.searchLoader = new Bunifu.UI.WinForms.BunifuLoader();
            this.productDataGridView = new System.Windows.Forms.DataGridView();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.categoryComboBox = new System.Windows.Forms.ComboBox();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.search_pro = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.uploadProductImageBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.productPicturebox = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.productPriceTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.productDescriptionTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.productNameTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.exportBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.searchTxtBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.saveBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.deleteBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.addBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.productDataGridView)).BeginInit();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.productPicturebox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // splitContainer1
            // 
            this.splitContainer1.Location = new System.Drawing.Point(6, 122);
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.searchLoader);
            this.splitContainer1.Panel1.Controls.Add(this.productDataGridView);
            this.splitContainer1.Panel1MinSize = 500;
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.AutoScroll = true;
            this.splitContainer1.Panel2.Controls.Add(this.bunifuShadowPanel1);
            this.splitContainer1.Panel2MinSize = 500;
            this.splitContainer1.Size = new System.Drawing.Size(1409, 596);
            this.splitContainer1.SplitterDistance = 725;
            this.splitContainer1.TabIndex = 23;
            // 
            // searchLoader
            // 
            this.searchLoader.AllowStylePresets = true;
            this.searchLoader.BackColor = System.Drawing.Color.Transparent;
            this.searchLoader.CapStyle = Bunifu.UI.WinForms.BunifuLoader.CapStyles.Round;
            this.searchLoader.Color = System.Drawing.Color.DodgerBlue;
            this.searchLoader.Colors = new Bunifu.UI.WinForms.Bloom[0];
            this.searchLoader.Customization = "";
            this.searchLoader.DashWidth = 0.5F;
            this.searchLoader.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.searchLoader.Image = null;
            this.searchLoader.Location = new System.Drawing.Point(263, 299);
            this.searchLoader.Name = "searchLoader";
            this.searchLoader.NoRounding = false;
            this.searchLoader.Preset = Bunifu.UI.WinForms.BunifuLoader.StylePresets.Solid;
            this.searchLoader.RingStyle = Bunifu.UI.WinForms.BunifuLoader.RingStyles.Solid;
            this.searchLoader.ShowText = false;
            this.searchLoader.Size = new System.Drawing.Size(40, 40);
            this.searchLoader.Speed = 7;
            this.searchLoader.TabIndex = 18;
            this.searchLoader.Text = "bunifuLoader1";
            this.searchLoader.TextPadding = new System.Windows.Forms.Padding(0);
            this.searchLoader.Thickness = 3;
            this.searchLoader.Transparent = true;
            // 
            // productDataGridView
            // 
            this.productDataGridView.AllowUserToDeleteRows = false;
            this.productDataGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.productDataGridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.productDataGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.productDataGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.CadetBlue;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Poppins", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.Color.CadetBlue;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.productDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.productDataGridView.ColumnHeadersHeight = 50;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Poppins SemiBold", 10F);
            dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.ControlLight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.productDataGridView.DefaultCellStyle = dataGridViewCellStyle2;
            this.productDataGridView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.productDataGridView.EnableHeadersVisualStyles = false;
            this.productDataGridView.Location = new System.Drawing.Point(0, 0);
            this.productDataGridView.Name = "productDataGridView";
            this.productDataGridView.RowHeadersVisible = false;
            this.productDataGridView.RowHeadersWidth = 62;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.Gray;
            this.productDataGridView.RowsDefaultCellStyle = dataGridViewCellStyle3;
            this.productDataGridView.RowTemplate.Height = 28;
            this.productDataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.productDataGridView.Size = new System.Drawing.Size(725, 596);
            this.productDataGridView.TabIndex = 17;
            this.productDataGridView.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.productDataGridView_CellClick);
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 20;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuShadowPanel1.Controls.Add(this.uploadProductImageBtn);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel6);
            this.bunifuShadowPanel1.Controls.Add(this.productPicturebox);
            this.bunifuShadowPanel1.Controls.Add(this.categoryComboBox);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel9);
            this.bunifuShadowPanel1.Controls.Add(this.productPriceTxt);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel7);
            this.bunifuShadowPanel1.Controls.Add(this.productDescriptionTxt);
            this.bunifuShadowPanel1.Controls.Add(this.productNameTxt);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(3, 3);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.White;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.ForwardDiagonal;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(674, 593);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 1;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Poppins SemiBold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(12, 405);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(86, 36);
            this.bunifuLabel6.TabIndex = 14;
            this.bunifuLabel6.Text = "Barcode";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // categoryComboBox
            // 
            this.categoryComboBox.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.categoryComboBox.FormattingEnabled = true;
            this.categoryComboBox.Items.AddRange(new object[] {
            "1",
            "2",
            "3"});
            this.categoryComboBox.Location = new System.Drawing.Point(132, 261);
            this.categoryComboBox.Name = "categoryComboBox";
            this.categoryComboBox.Size = new System.Drawing.Size(244, 21);
            this.categoryComboBox.TabIndex = 11;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Poppins SemiBold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel9.Location = new System.Drawing.Point(9, 261);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(96, 36);
            this.bunifuLabel9.TabIndex = 9;
            this.bunifuLabel9.Text = "Category";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Poppins SemiBold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.Location = new System.Drawing.Point(12, 349);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(50, 36);
            this.bunifuLabel7.TabIndex = 7;
            this.bunifuLabel7.Text = "Price";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Poppins SemiBold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(12, 110);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(117, 36);
            this.bunifuLabel3.TabIndex = 4;
            this.bunifuLabel3.Text = "Description";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Poppins SemiBold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(12, 13);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(145, 36);
            this.bunifuLabel2.TabIndex = 3;
            this.bunifuLabel2.Text = "Product name";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Poppins", 12F);
            this.bunifuLabel1.Location = new System.Drawing.Point(7, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(93, 42);
            this.bunifuLabel1.TabIndex = 16;
            this.bunifuLabel1.Text = "Product";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // search_pro
            // 
            this.search_pro.AllowAnimations = true;
            this.search_pro.AllowMouseEffects = true;
            this.search_pro.AllowToggling = false;
            this.search_pro.AnimationSpeed = 200;
            this.search_pro.AutoGenerateColors = false;
            this.search_pro.AutoRoundBorders = false;
            this.search_pro.AutoSizeLeftIcon = true;
            this.search_pro.AutoSizeRightIcon = true;
            this.search_pro.BackColor = System.Drawing.Color.Transparent;
            this.search_pro.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.search_pro.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("search_pro.BackgroundImage")));
            this.search_pro.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.search_pro.ButtonText = "Search";
            this.search_pro.ButtonTextMarginLeft = 0;
            this.search_pro.ColorContrastOnClick = 45;
            this.search_pro.ColorContrastOnHover = 45;
            this.search_pro.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.search_pro.CustomizableEdges = borderEdges2;
            this.search_pro.DialogResult = System.Windows.Forms.DialogResult.None;
            this.search_pro.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.search_pro.DisabledFillColor = System.Drawing.Color.Empty;
            this.search_pro.DisabledForecolor = System.Drawing.Color.Empty;
            this.search_pro.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.search_pro.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.search_pro.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.search_pro.IconLeft = null;
            this.search_pro.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.search_pro.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.search_pro.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.search_pro.IconMarginLeft = 11;
            this.search_pro.IconPadding = 10;
            this.search_pro.IconRight = null;
            this.search_pro.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.search_pro.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.search_pro.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.search_pro.IconSize = 25;
            this.search_pro.IdleBorderColor = System.Drawing.Color.Empty;
            this.search_pro.IdleBorderRadius = 0;
            this.search_pro.IdleBorderThickness = 0;
            this.search_pro.IdleFillColor = System.Drawing.Color.Empty;
            this.search_pro.IdleIconLeftImage = null;
            this.search_pro.IdleIconRightImage = null;
            this.search_pro.IndicateFocus = false;
            this.search_pro.Location = new System.Drawing.Point(618, 54);
            this.search_pro.Name = "search_pro";
            this.search_pro.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.search_pro.OnDisabledState.BorderRadius = 30;
            this.search_pro.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.search_pro.OnDisabledState.BorderThickness = 1;
            this.search_pro.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.search_pro.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.search_pro.OnDisabledState.IconLeftImage = null;
            this.search_pro.OnDisabledState.IconRightImage = null;
            this.search_pro.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.search_pro.onHoverState.BorderRadius = 30;
            this.search_pro.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.search_pro.onHoverState.BorderThickness = 1;
            this.search_pro.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.search_pro.onHoverState.ForeColor = System.Drawing.Color.White;
            this.search_pro.onHoverState.IconLeftImage = null;
            this.search_pro.onHoverState.IconRightImage = null;
            this.search_pro.OnIdleState.BorderColor = System.Drawing.Color.CadetBlue;
            this.search_pro.OnIdleState.BorderRadius = 30;
            this.search_pro.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.search_pro.OnIdleState.BorderThickness = 1;
            this.search_pro.OnIdleState.FillColor = System.Drawing.Color.CadetBlue;
            this.search_pro.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.search_pro.OnIdleState.IconLeftImage = null;
            this.search_pro.OnIdleState.IconRightImage = null;
            this.search_pro.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.search_pro.OnPressedState.BorderRadius = 30;
            this.search_pro.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.search_pro.OnPressedState.BorderThickness = 1;
            this.search_pro.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.search_pro.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.search_pro.OnPressedState.IconLeftImage = null;
            this.search_pro.OnPressedState.IconRightImage = null;
            this.search_pro.Size = new System.Drawing.Size(117, 51);
            this.search_pro.TabIndex = 24;
            this.search_pro.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.search_pro.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.search_pro.TextMarginLeft = 0;
            this.search_pro.TextPadding = new System.Windows.Forms.Padding(0);
            this.search_pro.UseDefaultRadiusAndThickness = true;
            this.search_pro.Click += new System.EventHandler(this.searchBtn_Click);
            // 
            // uploadProductImageBtn
            // 
            this.uploadProductImageBtn.AllowAnimations = true;
            this.uploadProductImageBtn.AllowMouseEffects = true;
            this.uploadProductImageBtn.AllowToggling = false;
            this.uploadProductImageBtn.AnimationSpeed = 200;
            this.uploadProductImageBtn.AutoGenerateColors = false;
            this.uploadProductImageBtn.AutoRoundBorders = false;
            this.uploadProductImageBtn.AutoSizeLeftIcon = true;
            this.uploadProductImageBtn.AutoSizeRightIcon = true;
            this.uploadProductImageBtn.BackColor = System.Drawing.Color.Transparent;
            this.uploadProductImageBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.uploadProductImageBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("uploadProductImageBtn.BackgroundImage")));
            this.uploadProductImageBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.uploadProductImageBtn.ButtonText = "Update";
            this.uploadProductImageBtn.ButtonTextMarginLeft = 0;
            this.uploadProductImageBtn.ColorContrastOnClick = 45;
            this.uploadProductImageBtn.ColorContrastOnHover = 45;
            this.uploadProductImageBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.uploadProductImageBtn.CustomizableEdges = borderEdges1;
            this.uploadProductImageBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.uploadProductImageBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.uploadProductImageBtn.DisabledFillColor = System.Drawing.Color.Empty;
            this.uploadProductImageBtn.DisabledForecolor = System.Drawing.Color.Empty;
            this.uploadProductImageBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.uploadProductImageBtn.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.uploadProductImageBtn.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.uploadProductImageBtn.IconLeft = null;
            this.uploadProductImageBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.uploadProductImageBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.uploadProductImageBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.uploadProductImageBtn.IconMarginLeft = 11;
            this.uploadProductImageBtn.IconPadding = 10;
            this.uploadProductImageBtn.IconRight = null;
            this.uploadProductImageBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.uploadProductImageBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.uploadProductImageBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.uploadProductImageBtn.IconSize = 25;
            this.uploadProductImageBtn.IdleBorderColor = System.Drawing.Color.Empty;
            this.uploadProductImageBtn.IdleBorderRadius = 0;
            this.uploadProductImageBtn.IdleBorderThickness = 0;
            this.uploadProductImageBtn.IdleFillColor = System.Drawing.Color.Empty;
            this.uploadProductImageBtn.IdleIconLeftImage = null;
            this.uploadProductImageBtn.IdleIconRightImage = null;
            this.uploadProductImageBtn.IndicateFocus = false;
            this.uploadProductImageBtn.Location = new System.Drawing.Point(443, 468);
            this.uploadProductImageBtn.Name = "uploadProductImageBtn";
            this.uploadProductImageBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.uploadProductImageBtn.OnDisabledState.BorderRadius = 30;
            this.uploadProductImageBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.uploadProductImageBtn.OnDisabledState.BorderThickness = 1;
            this.uploadProductImageBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.uploadProductImageBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.uploadProductImageBtn.OnDisabledState.IconLeftImage = null;
            this.uploadProductImageBtn.OnDisabledState.IconRightImage = null;
            this.uploadProductImageBtn.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.uploadProductImageBtn.onHoverState.BorderRadius = 30;
            this.uploadProductImageBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.uploadProductImageBtn.onHoverState.BorderThickness = 1;
            this.uploadProductImageBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.uploadProductImageBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.uploadProductImageBtn.onHoverState.IconLeftImage = null;
            this.uploadProductImageBtn.onHoverState.IconRightImage = null;
            this.uploadProductImageBtn.OnIdleState.BorderColor = System.Drawing.Color.CadetBlue;
            this.uploadProductImageBtn.OnIdleState.BorderRadius = 30;
            this.uploadProductImageBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.uploadProductImageBtn.OnIdleState.BorderThickness = 1;
            this.uploadProductImageBtn.OnIdleState.FillColor = System.Drawing.Color.CadetBlue;
            this.uploadProductImageBtn.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.uploadProductImageBtn.OnIdleState.IconLeftImage = null;
            this.uploadProductImageBtn.OnIdleState.IconRightImage = null;
            this.uploadProductImageBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.uploadProductImageBtn.OnPressedState.BorderRadius = 30;
            this.uploadProductImageBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.uploadProductImageBtn.OnPressedState.BorderThickness = 1;
            this.uploadProductImageBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.uploadProductImageBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.uploadProductImageBtn.OnPressedState.IconLeftImage = null;
            this.uploadProductImageBtn.OnPressedState.IconRightImage = null;
            this.uploadProductImageBtn.Size = new System.Drawing.Size(200, 40);
            this.uploadProductImageBtn.TabIndex = 25;
            this.uploadProductImageBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.uploadProductImageBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.uploadProductImageBtn.TextMarginLeft = 0;
            this.uploadProductImageBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.uploadProductImageBtn.UseDefaultRadiusAndThickness = true;
            this.uploadProductImageBtn.Click += new System.EventHandler(this.uploadProductImageBtn_Click);
            // 
            // productPicturebox
            // 
            this.productPicturebox.AllowFocused = false;
            this.productPicturebox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.productPicturebox.AutoSizeHeight = true;
            this.productPicturebox.BorderRadius = 0;
            this.productPicturebox.Image = ((System.Drawing.Image)(resources.GetObject("productPicturebox.Image")));
            this.productPicturebox.IsCircle = false;
            this.productPicturebox.Location = new System.Drawing.Point(443, 241);
            this.productPicturebox.Name = "productPicturebox";
            this.productPicturebox.Size = new System.Drawing.Size(200, 200);
            this.productPicturebox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.productPicturebox.TabIndex = 13;
            this.productPicturebox.TabStop = false;
            this.productPicturebox.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // productPriceTxt
            // 
            this.productPriceTxt.AcceptsReturn = false;
            this.productPriceTxt.AcceptsTab = false;
            this.productPriceTxt.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.productPriceTxt.AnimationSpeed = 0;
            this.productPriceTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.productPriceTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.productPriceTxt.AutoSizeHeight = true;
            this.productPriceTxt.BackColor = System.Drawing.Color.Transparent;
            this.productPriceTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productPriceTxt.BackgroundImage")));
            this.productPriceTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.productPriceTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productPriceTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.productPriceTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.productPriceTxt.BorderRadius = 20;
            this.productPriceTxt.BorderThickness = 1;
            this.productPriceTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.productPriceTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.productPriceTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.productPriceTxt.DefaultFont = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.productPriceTxt.DefaultText = "";
            this.productPriceTxt.FillColor = System.Drawing.Color.White;
            this.productPriceTxt.HideSelection = true;
            this.productPriceTxt.IconLeft = null;
            this.productPriceTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.productPriceTxt.IconPadding = 10;
            this.productPriceTxt.IconRight = null;
            this.productPriceTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.productPriceTxt.Lines = new string[0];
            this.productPriceTxt.Location = new System.Drawing.Point(133, 344);
            this.productPriceTxt.MaxLength = 32767;
            this.productPriceTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.productPriceTxt.Modified = false;
            this.productPriceTxt.Multiline = false;
            this.productPriceTxt.Name = "productPriceTxt";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productPriceTxt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.productPriceTxt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productPriceTxt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productPriceTxt.OnIdleState = stateProperties4;
            this.productPriceTxt.Padding = new System.Windows.Forms.Padding(3);
            this.productPriceTxt.PasswordChar = '\0';
            this.productPriceTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.productPriceTxt.PlaceholderText = "0.0";
            this.productPriceTxt.ReadOnly = false;
            this.productPriceTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.productPriceTxt.SelectedText = "";
            this.productPriceTxt.SelectionLength = 0;
            this.productPriceTxt.SelectionStart = 0;
            this.productPriceTxt.ShortcutsEnabled = true;
            this.productPriceTxt.Size = new System.Drawing.Size(304, 38);
            this.productPriceTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.productPriceTxt.TabIndex = 12;
            this.productPriceTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.productPriceTxt.TextMarginBottom = 0;
            this.productPriceTxt.TextMarginLeft = 3;
            this.productPriceTxt.TextMarginTop = 1;
            this.productPriceTxt.TextPlaceholder = "0.0";
            this.productPriceTxt.UseSystemPasswordChar = false;
            this.productPriceTxt.WordWrap = true;
            // 
            // productDescriptionTxt
            // 
            this.productDescriptionTxt.AcceptsReturn = false;
            this.productDescriptionTxt.AcceptsTab = false;
            this.productDescriptionTxt.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.productDescriptionTxt.AnimationSpeed = 0;
            this.productDescriptionTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.productDescriptionTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.productDescriptionTxt.AutoSizeHeight = true;
            this.productDescriptionTxt.BackColor = System.Drawing.Color.Transparent;
            this.productDescriptionTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productDescriptionTxt.BackgroundImage")));
            this.productDescriptionTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.productDescriptionTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productDescriptionTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.productDescriptionTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.productDescriptionTxt.BorderRadius = 20;
            this.productDescriptionTxt.BorderThickness = 1;
            this.productDescriptionTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.productDescriptionTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.productDescriptionTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.productDescriptionTxt.DefaultFont = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.productDescriptionTxt.DefaultText = "";
            this.productDescriptionTxt.FillColor = System.Drawing.Color.White;
            this.productDescriptionTxt.HideSelection = true;
            this.productDescriptionTxt.IconLeft = null;
            this.productDescriptionTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.productDescriptionTxt.IconPadding = 10;
            this.productDescriptionTxt.IconRight = null;
            this.productDescriptionTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.productDescriptionTxt.Lines = new string[0];
            this.productDescriptionTxt.Location = new System.Drawing.Point(12, 146);
            this.productDescriptionTxt.MaxLength = 32767;
            this.productDescriptionTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.productDescriptionTxt.Modified = false;
            this.productDescriptionTxt.Multiline = true;
            this.productDescriptionTxt.Name = "productDescriptionTxt";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productDescriptionTxt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.productDescriptionTxt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productDescriptionTxt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productDescriptionTxt.OnIdleState = stateProperties8;
            this.productDescriptionTxt.Padding = new System.Windows.Forms.Padding(3);
            this.productDescriptionTxt.PasswordChar = '\0';
            this.productDescriptionTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.productDescriptionTxt.PlaceholderText = "Type product description here ...";
            this.productDescriptionTxt.ReadOnly = false;
            this.productDescriptionTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.productDescriptionTxt.SelectedText = "";
            this.productDescriptionTxt.SelectionLength = 0;
            this.productDescriptionTxt.SelectionStart = 0;
            this.productDescriptionTxt.ShortcutsEnabled = true;
            this.productDescriptionTxt.Size = new System.Drawing.Size(631, 69);
            this.productDescriptionTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.productDescriptionTxt.TabIndex = 6;
            this.productDescriptionTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.productDescriptionTxt.TextMarginBottom = 0;
            this.productDescriptionTxt.TextMarginLeft = 3;
            this.productDescriptionTxt.TextMarginTop = 1;
            this.productDescriptionTxt.TextPlaceholder = "Type product description here ...";
            this.productDescriptionTxt.UseSystemPasswordChar = false;
            this.productDescriptionTxt.WordWrap = true;
            // 
            // productNameTxt
            // 
            this.productNameTxt.AcceptsReturn = false;
            this.productNameTxt.AcceptsTab = false;
            this.productNameTxt.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.productNameTxt.AnimationSpeed = 0;
            this.productNameTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.productNameTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.productNameTxt.AutoSizeHeight = true;
            this.productNameTxt.BackColor = System.Drawing.Color.Transparent;
            this.productNameTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productNameTxt.BackgroundImage")));
            this.productNameTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.productNameTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productNameTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.productNameTxt.BorderColorIdle = System.Drawing.Color.Silver;
            this.productNameTxt.BorderRadius = 20;
            this.productNameTxt.BorderThickness = 1;
            this.productNameTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.productNameTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.productNameTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.productNameTxt.DefaultFont = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.productNameTxt.DefaultText = "";
            this.productNameTxt.FillColor = System.Drawing.Color.White;
            this.productNameTxt.HideSelection = true;
            this.productNameTxt.IconLeft = null;
            this.productNameTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.productNameTxt.IconPadding = 10;
            this.productNameTxt.IconRight = null;
            this.productNameTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.productNameTxt.Lines = new string[0];
            this.productNameTxt.Location = new System.Drawing.Point(12, 49);
            this.productNameTxt.MaxLength = 32767;
            this.productNameTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.productNameTxt.Modified = false;
            this.productNameTxt.Multiline = false;
            this.productNameTxt.Name = "productNameTxt";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productNameTxt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.productNameTxt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productNameTxt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productNameTxt.OnIdleState = stateProperties12;
            this.productNameTxt.Padding = new System.Windows.Forms.Padding(3);
            this.productNameTxt.PasswordChar = '\0';
            this.productNameTxt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.productNameTxt.PlaceholderText = "Type product name here ...";
            this.productNameTxt.ReadOnly = false;
            this.productNameTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.productNameTxt.SelectedText = "";
            this.productNameTxt.SelectionLength = 0;
            this.productNameTxt.SelectionStart = 0;
            this.productNameTxt.ShortcutsEnabled = true;
            this.productNameTxt.Size = new System.Drawing.Size(631, 43);
            this.productNameTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.productNameTxt.TabIndex = 5;
            this.productNameTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.productNameTxt.TextMarginBottom = 0;
            this.productNameTxt.TextMarginLeft = 3;
            this.productNameTxt.TextMarginTop = 1;
            this.productNameTxt.TextPlaceholder = "Type product name here ...";
            this.productNameTxt.UseSystemPasswordChar = false;
            this.productNameTxt.WordWrap = true;
            // 
            // exportBtn
            // 
            this.exportBtn.AllowAnimations = false;
            this.exportBtn.AllowMouseEffects = true;
            this.exportBtn.AllowToggling = false;
            this.exportBtn.AnimationSpeed = 200;
            this.exportBtn.AutoGenerateColors = false;
            this.exportBtn.AutoRoundBorders = false;
            this.exportBtn.AutoSizeLeftIcon = true;
            this.exportBtn.AutoSizeRightIcon = true;
            this.exportBtn.BackColor = System.Drawing.Color.Transparent;
            this.exportBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(194)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            this.exportBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("exportBtn.BackgroundImage")));
            this.exportBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.exportBtn.ButtonText = "Export";
            this.exportBtn.ButtonTextMarginLeft = 0;
            this.exportBtn.ColorContrastOnClick = 45;
            this.exportBtn.ColorContrastOnHover = 45;
            this.exportBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.exportBtn.CustomizableEdges = borderEdges3;
            this.exportBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.exportBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.exportBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.exportBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.exportBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.exportBtn.Font = new System.Drawing.Font("Poppins", 12F);
            this.exportBtn.ForeColor = System.Drawing.Color.Teal;
            this.exportBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.exportBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.exportBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.exportBtn.IconMarginLeft = 11;
            this.exportBtn.IconPadding = 10;
            this.exportBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.exportBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.exportBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.exportBtn.IconSize = 25;
            this.exportBtn.IdleBorderColor = System.Drawing.Color.White;
            this.exportBtn.IdleBorderRadius = 30;
            this.exportBtn.IdleBorderThickness = 1;
            this.exportBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(194)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            this.exportBtn.IdleIconLeftImage = null;
            this.exportBtn.IdleIconRightImage = global::GUI.Properties.Resources.arrow_small_down;
            this.exportBtn.IndicateFocus = false;
            this.exportBtn.Location = new System.Drawing.Point(1075, 54);
            this.exportBtn.Name = "exportBtn";
            this.exportBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.exportBtn.OnDisabledState.BorderRadius = 30;
            this.exportBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.exportBtn.OnDisabledState.BorderThickness = 1;
            this.exportBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.exportBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.exportBtn.OnDisabledState.IconLeftImage = null;
            this.exportBtn.OnDisabledState.IconRightImage = null;
            this.exportBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.exportBtn.onHoverState.BorderRadius = 30;
            this.exportBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.exportBtn.onHoverState.BorderThickness = 1;
            this.exportBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.exportBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.exportBtn.onHoverState.IconLeftImage = null;
            this.exportBtn.onHoverState.IconRightImage = null;
            this.exportBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.exportBtn.OnIdleState.BorderRadius = 30;
            this.exportBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.exportBtn.OnIdleState.BorderThickness = 1;
            this.exportBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(194)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            this.exportBtn.OnIdleState.ForeColor = System.Drawing.Color.Teal;
            this.exportBtn.OnIdleState.IconLeftImage = null;
            this.exportBtn.OnIdleState.IconRightImage = global::GUI.Properties.Resources.arrow_small_down;
            this.exportBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.exportBtn.OnPressedState.BorderRadius = 30;
            this.exportBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.exportBtn.OnPressedState.BorderThickness = 1;
            this.exportBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.exportBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.exportBtn.OnPressedState.IconLeftImage = null;
            this.exportBtn.OnPressedState.IconRightImage = null;
            this.exportBtn.Size = new System.Drawing.Size(120, 47);
            this.exportBtn.TabIndex = 20;
            this.exportBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.exportBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.exportBtn.TextMarginLeft = 0;
            this.exportBtn.TextPadding = new System.Windows.Forms.Padding(5, 2, 0, 0);
            this.exportBtn.UseDefaultRadiusAndThickness = true;
            // 
            // searchTxtBox
            // 
            this.searchTxtBox.AcceptsReturn = false;
            this.searchTxtBox.AcceptsTab = false;
            this.searchTxtBox.AnimationSpeed = 200;
            this.searchTxtBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.searchTxtBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.searchTxtBox.AutoSizeHeight = true;
            this.searchTxtBox.BackColor = System.Drawing.Color.Transparent;
            this.searchTxtBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchTxtBox.BackgroundImage")));
            this.searchTxtBox.BorderColorActive = System.Drawing.Color.Silver;
            this.searchTxtBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchTxtBox.BorderColorHover = System.Drawing.Color.Silver;
            this.searchTxtBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.searchTxtBox.BorderRadius = 40;
            this.searchTxtBox.BorderThickness = 1;
            this.searchTxtBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.searchTxtBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.searchTxtBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.searchTxtBox.DefaultFont = new System.Drawing.Font("Poppins", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.searchTxtBox.DefaultText = "";
            this.searchTxtBox.FillColor = System.Drawing.Color.White;
            this.searchTxtBox.HideSelection = true;
            this.searchTxtBox.IconLeft = null;
            this.searchTxtBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchTxtBox.IconPadding = 10;
            this.searchTxtBox.IconRight = null;
            this.searchTxtBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchTxtBox.Lines = new string[0];
            this.searchTxtBox.Location = new System.Drawing.Point(7, 54);
            this.searchTxtBox.MaxLength = 32767;
            this.searchTxtBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.searchTxtBox.Modified = false;
            this.searchTxtBox.Multiline = false;
            this.searchTxtBox.Name = "searchTxtBox";
            stateProperties13.BorderColor = System.Drawing.Color.Silver;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchTxtBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.searchTxtBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Silver;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchTxtBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchTxtBox.OnIdleState = stateProperties16;
            this.searchTxtBox.Padding = new System.Windows.Forms.Padding(3);
            this.searchTxtBox.PasswordChar = '\0';
            this.searchTxtBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.searchTxtBox.PlaceholderText = "Search product ...";
            this.searchTxtBox.ReadOnly = false;
            this.searchTxtBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.searchTxtBox.SelectedText = "";
            this.searchTxtBox.SelectionLength = 0;
            this.searchTxtBox.SelectionStart = 0;
            this.searchTxtBox.ShortcutsEnabled = true;
            this.searchTxtBox.Size = new System.Drawing.Size(596, 51);
            this.searchTxtBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.searchTxtBox.TabIndex = 17;
            this.searchTxtBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.searchTxtBox.TextMarginBottom = 0;
            this.searchTxtBox.TextMarginLeft = 3;
            this.searchTxtBox.TextMarginTop = 1;
            this.searchTxtBox.TextPlaceholder = "Search product ...";
            this.searchTxtBox.UseSystemPasswordChar = false;
            this.searchTxtBox.WordWrap = true;
            // 
            // saveBtn
            // 
            this.saveBtn.AllowAnimations = false;
            this.saveBtn.AllowMouseEffects = true;
            this.saveBtn.AllowToggling = false;
            this.saveBtn.AnimationSpeed = 200;
            this.saveBtn.AutoGenerateColors = false;
            this.saveBtn.AutoRoundBorders = false;
            this.saveBtn.AutoSizeLeftIcon = true;
            this.saveBtn.AutoSizeRightIcon = true;
            this.saveBtn.BackColor = System.Drawing.Color.Transparent;
            this.saveBtn.BackColor1 = System.Drawing.Color.CadetBlue;
            this.saveBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("saveBtn.BackgroundImage")));
            this.saveBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.saveBtn.ButtonText = "Save";
            this.saveBtn.ButtonTextMarginLeft = 0;
            this.saveBtn.ColorContrastOnClick = 45;
            this.saveBtn.ColorContrastOnHover = 45;
            this.saveBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.saveBtn.CustomizableEdges = borderEdges4;
            this.saveBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.saveBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.saveBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.saveBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.saveBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.saveBtn.Font = new System.Drawing.Font("Poppins", 12F);
            this.saveBtn.ForeColor = System.Drawing.Color.White;
            this.saveBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.saveBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.saveBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.saveBtn.IconMarginLeft = 11;
            this.saveBtn.IconPadding = 10;
            this.saveBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.saveBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.saveBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.saveBtn.IconSize = 25;
            this.saveBtn.IdleBorderColor = System.Drawing.Color.White;
            this.saveBtn.IdleBorderRadius = 30;
            this.saveBtn.IdleBorderThickness = 1;
            this.saveBtn.IdleFillColor = System.Drawing.Color.CadetBlue;
            this.saveBtn.IdleIconLeftImage = null;
            this.saveBtn.IdleIconRightImage = global::GUI.Properties.Resources.pencil;
            this.saveBtn.IndicateFocus = false;
            this.saveBtn.Location = new System.Drawing.Point(1167, 724);
            this.saveBtn.Name = "saveBtn";
            this.saveBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.saveBtn.OnDisabledState.BorderRadius = 30;
            this.saveBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.saveBtn.OnDisabledState.BorderThickness = 1;
            this.saveBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.saveBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.saveBtn.OnDisabledState.IconLeftImage = null;
            this.saveBtn.OnDisabledState.IconRightImage = null;
            this.saveBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.saveBtn.onHoverState.BorderRadius = 30;
            this.saveBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.saveBtn.onHoverState.BorderThickness = 1;
            this.saveBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.saveBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.saveBtn.onHoverState.IconLeftImage = null;
            this.saveBtn.onHoverState.IconRightImage = null;
            this.saveBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.saveBtn.OnIdleState.BorderRadius = 30;
            this.saveBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.saveBtn.OnIdleState.BorderThickness = 1;
            this.saveBtn.OnIdleState.FillColor = System.Drawing.Color.CadetBlue;
            this.saveBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.saveBtn.OnIdleState.IconLeftImage = null;
            this.saveBtn.OnIdleState.IconRightImage = global::GUI.Properties.Resources.pencil;
            this.saveBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.saveBtn.OnPressedState.BorderRadius = 30;
            this.saveBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.saveBtn.OnPressedState.BorderThickness = 1;
            this.saveBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.saveBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.saveBtn.OnPressedState.IconLeftImage = null;
            this.saveBtn.OnPressedState.IconRightImage = null;
            this.saveBtn.Size = new System.Drawing.Size(101, 47);
            this.saveBtn.TabIndex = 22;
            this.saveBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.saveBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.saveBtn.TextMarginLeft = 0;
            this.saveBtn.TextPadding = new System.Windows.Forms.Padding(5, 2, 0, 0);
            this.saveBtn.UseDefaultRadiusAndThickness = true;
            this.saveBtn.Click += new System.EventHandler(this.saveBtn_Click);
            // 
            // deleteBtn
            // 
            this.deleteBtn.AllowAnimations = false;
            this.deleteBtn.AllowMouseEffects = true;
            this.deleteBtn.AllowToggling = false;
            this.deleteBtn.AnimationSpeed = 200;
            this.deleteBtn.AutoGenerateColors = false;
            this.deleteBtn.AutoRoundBorders = false;
            this.deleteBtn.AutoSizeLeftIcon = true;
            this.deleteBtn.AutoSizeRightIcon = true;
            this.deleteBtn.BackColor = System.Drawing.Color.Transparent;
            this.deleteBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.deleteBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("deleteBtn.BackgroundImage")));
            this.deleteBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.deleteBtn.ButtonText = "Delete";
            this.deleteBtn.ButtonTextMarginLeft = 0;
            this.deleteBtn.ColorContrastOnClick = 45;
            this.deleteBtn.ColorContrastOnHover = 45;
            this.deleteBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.deleteBtn.CustomizableEdges = borderEdges5;
            this.deleteBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.deleteBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.deleteBtn.Font = new System.Drawing.Font("Poppins", 12F);
            this.deleteBtn.ForeColor = System.Drawing.Color.White;
            this.deleteBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.deleteBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.deleteBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.deleteBtn.IconMarginLeft = 11;
            this.deleteBtn.IconPadding = 10;
            this.deleteBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.deleteBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.deleteBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.deleteBtn.IconSize = 25;
            this.deleteBtn.IdleBorderColor = System.Drawing.Color.White;
            this.deleteBtn.IdleBorderRadius = 30;
            this.deleteBtn.IdleBorderThickness = 1;
            this.deleteBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.deleteBtn.IdleIconLeftImage = null;
            this.deleteBtn.IdleIconRightImage = global::GUI.Properties.Resources.trash;
            this.deleteBtn.IndicateFocus = false;
            this.deleteBtn.Location = new System.Drawing.Point(1298, 724);
            this.deleteBtn.Name = "deleteBtn";
            this.deleteBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteBtn.OnDisabledState.BorderRadius = 30;
            this.deleteBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.deleteBtn.OnDisabledState.BorderThickness = 1;
            this.deleteBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteBtn.OnDisabledState.IconLeftImage = null;
            this.deleteBtn.OnDisabledState.IconRightImage = null;
            this.deleteBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.deleteBtn.onHoverState.BorderRadius = 30;
            this.deleteBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.deleteBtn.onHoverState.BorderThickness = 1;
            this.deleteBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.deleteBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.deleteBtn.onHoverState.IconLeftImage = null;
            this.deleteBtn.onHoverState.IconRightImage = null;
            this.deleteBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.deleteBtn.OnIdleState.BorderRadius = 30;
            this.deleteBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.deleteBtn.OnIdleState.BorderThickness = 1;
            this.deleteBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.deleteBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.deleteBtn.OnIdleState.IconLeftImage = null;
            this.deleteBtn.OnIdleState.IconRightImage = global::GUI.Properties.Resources.trash;
            this.deleteBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.deleteBtn.OnPressedState.BorderRadius = 30;
            this.deleteBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.deleteBtn.OnPressedState.BorderThickness = 1;
            this.deleteBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.deleteBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.deleteBtn.OnPressedState.IconLeftImage = null;
            this.deleteBtn.OnPressedState.IconRightImage = null;
            this.deleteBtn.Size = new System.Drawing.Size(117, 47);
            this.deleteBtn.TabIndex = 21;
            this.deleteBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.deleteBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.deleteBtn.TextMarginLeft = 0;
            this.deleteBtn.TextPadding = new System.Windows.Forms.Padding(5, 2, 0, 0);
            this.deleteBtn.UseDefaultRadiusAndThickness = true;
            this.deleteBtn.Click += new System.EventHandler(this.deleteBtn_Click);
            // 
            // addBtn
            // 
            this.addBtn.AllowAnimations = false;
            this.addBtn.AllowMouseEffects = true;
            this.addBtn.AllowToggling = false;
            this.addBtn.AnimationSpeed = 200;
            this.addBtn.AutoGenerateColors = false;
            this.addBtn.AutoRoundBorders = false;
            this.addBtn.AutoSizeLeftIcon = true;
            this.addBtn.AutoSizeRightIcon = true;
            this.addBtn.BackColor = System.Drawing.Color.Transparent;
            this.addBtn.BackColor1 = System.Drawing.Color.CadetBlue;
            this.addBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addBtn.BackgroundImage")));
            this.addBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.ButtonText = "Add";
            this.addBtn.ButtonTextMarginLeft = 0;
            this.addBtn.ColorContrastOnClick = 45;
            this.addBtn.ColorContrastOnHover = 45;
            this.addBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.addBtn.CustomizableEdges = borderEdges6;
            this.addBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.addBtn.Font = new System.Drawing.Font("Poppins", 12F);
            this.addBtn.ForeColor = System.Drawing.Color.White;
            this.addBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addBtn.IconMarginLeft = 11;
            this.addBtn.IconPadding = 10;
            this.addBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addBtn.IconSize = 25;
            this.addBtn.IdleBorderColor = System.Drawing.Color.White;
            this.addBtn.IdleBorderRadius = 30;
            this.addBtn.IdleBorderThickness = 1;
            this.addBtn.IdleFillColor = System.Drawing.Color.CadetBlue;
            this.addBtn.IdleIconLeftImage = null;
            this.addBtn.IdleIconRightImage = global::GUI.Properties.Resources.plus_small;
            this.addBtn.IndicateFocus = false;
            this.addBtn.Location = new System.Drawing.Point(1029, 724);
            this.addBtn.Name = "addBtn";
            this.addBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addBtn.OnDisabledState.BorderRadius = 30;
            this.addBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.OnDisabledState.BorderThickness = 1;
            this.addBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addBtn.OnDisabledState.IconLeftImage = null;
            this.addBtn.OnDisabledState.IconRightImage = null;
            this.addBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addBtn.onHoverState.BorderRadius = 30;
            this.addBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.onHoverState.BorderThickness = 1;
            this.addBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addBtn.onHoverState.IconLeftImage = null;
            this.addBtn.onHoverState.IconRightImage = null;
            this.addBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.addBtn.OnIdleState.BorderRadius = 30;
            this.addBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.OnIdleState.BorderThickness = 1;
            this.addBtn.OnIdleState.FillColor = System.Drawing.Color.CadetBlue;
            this.addBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.addBtn.OnIdleState.IconLeftImage = null;
            this.addBtn.OnIdleState.IconRightImage = global::GUI.Properties.Resources.plus_small;
            this.addBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addBtn.OnPressedState.BorderRadius = 30;
            this.addBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.OnPressedState.BorderThickness = 1;
            this.addBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addBtn.OnPressedState.IconLeftImage = null;
            this.addBtn.OnPressedState.IconRightImage = null;
            this.addBtn.Size = new System.Drawing.Size(98, 47);
            this.addBtn.TabIndex = 19;
            this.addBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addBtn.TextMarginLeft = 0;
            this.addBtn.TextPadding = new System.Windows.Forms.Padding(5, 2, 0, 0);
            this.addBtn.UseDefaultRadiusAndThickness = true;
            this.addBtn.Click += new System.EventHandler(this.addBtn_Click);
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = false;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(133, 405);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(159, 159);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 26;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // ProductManagement
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.search_pro);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.exportBtn);
            this.Controls.Add(this.searchTxtBox);
            this.Controls.Add(this.saveBtn);
            this.Controls.Add(this.deleteBtn);
            this.Controls.Add(this.addBtn);
            this.Name = "ProductManagement";
            this.Size = new System.Drawing.Size(1433, 790);
            this.Load += new System.EventHandler(this.ProductManagement_Load);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.productDataGridView)).EndInit();
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.productPicturebox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.DataGridView productDataGridView;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuPictureBox productPicturebox;
        private System.Windows.Forms.ComboBox categoryComboBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox productPriceTxt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox productDescriptionTxt;
        private Bunifu.UI.WinForms.BunifuTextBox productNameTxt;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 exportBtn;
        private Bunifu.UI.WinForms.BunifuTextBox searchTxtBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 saveBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 deleteBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 addBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton search_pro;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton uploadProductImageBtn;
        private Bunifu.UI.WinForms.BunifuLoader searchLoader;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
    }
}
